export type Pillar = 'Consult' | 'Build' | 'Ship';

export type Insight = {
  slug: string;
  title: string;
  dek: string;
  pillar: Pillar;
  date: string; // ISO
  dateModified?: string; // ISO — defaults to `date` if omitted
  readingMinutes: number;
  tags: string[];
  body: string[]; // paragraphs (Markdown-ish, kept simple for placeholders)
};

export const INSIGHTS: Insight[] = [
  {
    slug: 'google-io-hackathon-managed-agents-omni-antigravity',
    title: 'Inside the Google I/O Hackathon: 150 Builders, Managed Agents, and the New Google Agent Stack.',
    dek: 'Forty-eight hours after Google DeepMind shipped Gemini Omni, Antigravity 2.0, and the new Managed Agents API at I/O 2026, Cerebral Valley convened 150-plus builders at SHACK15 in San Francisco. I was in the room as a Google partner — not a competitor — to talk to builders, observe the new stack under load, and feature the work that will matter twelve months from now. Part 1 of a two-part series on Google I/O 2026.',
    pillar: 'Build',
    date: '2026-05-26',
    readingMinutes: 8,
    tags: ['Google I/O', 'Gemini Omni', 'Antigravity 2.0', 'Managed Agents', 'Google DeepMind', 'Cerebral Valley', 'AI Agents', 'Hackathon', 'Agentic Systems', 'Gemini 3.5 Flash', 'Fortune 500', 'AI Strategy'],
    body: [
      'My friend [Yves Hughes](https://www.linkedin.com/in/yvesjr/) just won 3rd place at the Google I/O Hackathon — and the bonus track for **Managed Agents**, the marquee Google announcement of I/O 2026. He beat more than 150 competing submissions over a single Saturday. I was in the room.',
      'Forty-eight hours earlier, on May 19, Google DeepMind [announced Gemini Omni, Antigravity 2.0, the new Managed Agents API, and Gemini 3.5 Flash](https://blog.google/innovation-and-ai/technology/developers-tools/google-io-2026-developer-highlights/) at the I/O 2026 keynote. By Saturday morning, Cerebral Valley had convened 150-plus builders at SHACK15 in San Francisco to be the first to ship on a stack that had not existed at the start of the work week. The fastest path from a Google product launch to a production implementation is now measured in hours, not quarters.',
      'I attended as a Google partner — not as a hackathon competitor. The job was to talk to builders, observe what they were trying to push the new APIs to do, and surface the work I expect to be referencing in Fortune 500 client conversations through the rest of 2026. Yves\' win is the first of those references. This article is the rest.',
      '![Google I/O Hackathon by Cerebral Valley — May 23, 2026, SHACK15 San Francisco](/images/insights/google-io-hackathon-06.jpg)',
      '## What Google Shipped on Monday That Made the Weekend Possible',
      'The I/O 2026 keynote was not a model launch. It was the unveiling of a coherent agent stack — four announcements that fit together as a single platform play.',
      '**Gemini Omni** is Google DeepMind\'s new world model — an any-to-any generative system that fuses Gemini reasoning with DeepMind\'s Veo, Nano Banana, and Genie components. The keynote demo was a glass marble rolling down a complex chain-reaction track, with the model anticipating physics, gravity, and kinetic motion at every frame. Omni does not just generate video. It predicts what should happen in a physical world and renders accordingly.',
      '**Antigravity 2.0** is the platform\'s biggest reset since it launched in November 2025. The product no longer centers on a code editor. It centers on the agent. A manager agent decomposes a task into subtasks, then dispatches specialized agents in parallel — one writing code, one running terminal commands, one testing in the browser — all coordinated through an SDK co-optimized for Gemini 3.5 Flash. DeepMind engineer Varun Mohan demoed it [building a functioning operating system from scratch in twelve hours](https://blog.google/innovation-and-ai/technology/developers-tools/google-io-2026-developer-highlights/). The platform also integrates **CodeMender**, DeepMind\'s autonomous security agent, which has already upstreamed 72 security fixes to open-source projects across codebases up to 4.5 million lines.',
      '**Gemini 3.5 Flash** is the engine making everything run. It outperforms Gemini 3.1 Pro across almost every benchmark while running four times faster than peer frontier models. The strategic point Google made on stage was unambiguous: Flash is not a budget tier. Flash is the new default for production agentic workflows.',
      '**Managed Agents** is the API that ties the stack together. With a single call, developers can now spin up an agent that reasons, uses tools, and executes code inside an isolated Linux environment — powered by the Antigravity agent harness, built on Gemini 3.5 Flash, available through the Interactions API and Google AI Studio. This was the launch the hackathon was specifically designed to stress-test.',
      '![Inside SHACK15 — Cerebral Valley × Google I/O Hackathon, the largest turnout in the series to date](/images/insights/google-io-hackathon-03.jpg)',
      '## Three Strategic Takeaways From the Weekend',
      'Beyond the leaderboard, three patterns surfaced across the room. These are the patterns I am taking into Fortune 500 client conversations this week.',
      '**Multi-agent orchestration is becoming the default.** Antigravity 2.0\'s manager-and-specialist pattern is not a feature. It is a re-architecture. Builders who started Saturday morning with single-agent loops finished the day with multi-agent compositions. Single-agent frameworks will look quaint within six months. Enterprise architects who are still scoping "pilot one AI assistant" should re-scope to "pilot a team of agents."',
      '**Managed Agents collapses the production-agent learning curve.** What used to take an enterprise platform team six weeks of harness work — sandboxing, tool routing, code execution isolation — Google now ships as a single API call. For Fortune 500 transformation programs, this changes the build-versus-buy math on every agent initiative. The question is no longer "can we build the harness?" It is "do we still need our own harness, or do we adopt Managed Agents and redirect that engineering capacity to domain logic?"',
      '**Omni\'s world model is a separate strategy entirely.** Most of the room was head-down on Managed Agents and Antigravity. Omni was largely treated as future-state. That is a tell. Omni\'s physics-aware video generation is going to reprice product visualization, robotics simulation, and high-volume training content over the next twelve months — but the enterprise adoption curve is slower than the agent stack. CMOs and Chief Innovation Officers who pre-stage their Omni evaluation now will move faster than the ones who wait for the case studies.',
      '![Bay Bridge view from SHACK15 — builders shipping on Gemini 3.5 Flash and the Managed Agents API, 48 hours after Google I/O 2026](/images/insights/google-io-hackathon-04.jpg)',
      '## Featured Builder: Yves Hughes Won the Marquee Track',
      '[Yves Hughes](https://www.linkedin.com/in/yvesjr/) — AI Executive Coach and self-described "Enterprise PM who is actively building AI" — took home 3rd place at the Google I/O Hackathon and won the dedicated bonus track for **Managed Agents**. The Managed Agents bonus was, by any honest measure, the marquee category of the weekend. Managed Agents was Google\'s headline launch on Monday. Three days later, Yves had shipped the implementation that beat more than 150 competing builds on the metric Google itself defined as the prize.',
      'What makes this notable is not just the medal. It is the positioning. Yves is not a twenty-two-year-old infrastructure engineer. He is a senior enterprise product leader and AI executive coach who put his name on a Managed Agents implementation that won inside Google\'s own house — against a room that included seasoned platform engineers and YC-backed founders. The signal — that experienced enterprise builders can outship pure infrastructure specialists on the new frontier stack — is the same signal Enso Labs is built on.',
      'Yves\' full post on the win, with hackathon photos: **[LinkedIn →](https://www.linkedin.com/posts/yvesjr_just-won-3rd-at-the-google-io-hackathon-activity-7464175320552607744-JLrX)**',
      '## What This Means for Fortune 500 AI Strategy',
      'The Google I/O 2026 announcement was not a model launch. It was a coherent agent stack. Omni handles world modeling and multimodal generation. Antigravity 2.0 handles multi-agent orchestration and autonomous coding. Managed Agents handles the production runtime. Gemini 3.5 Flash is the engine underneath all of it. For the first time, Google is competing on a stack that matches the depth of the Anthropic and OpenAI agent platforms — and on multi-agent orchestration with security baked in via CodeMender, Google is now ahead.',
      'For the Fortune 500 transformation leaders we work with, this is the moment to do three things in the next ninety days. First, run a Managed Agents pilot against one production workflow already running on a custom harness — measure the engineering capacity you free up. Second, evaluate Antigravity 2.0 in one engineering team and quantify the velocity delta versus your existing toolchain. Third, commission an Omni feasibility study against your largest existing video, training, or product visualization spend line. None of these is a 2027 decision. Each one is decidable by the end of Q3.',
      '![SHACK15 at the San Francisco Ferry Building — venue for the Cerebral Valley × Google I/O Hackathon](/images/insights/google-io-hackathon-01.jpg)',
      '## What Comes Next',
      'Cerebral Valley\'s next stop is Paris in July — the [RAISE Summit](https://raisesummit.com/) on July 4 and 5, followed by the Machina Hackathon on July 6. Google also announced the [Build with Gemini XPRIZE](https://www.xprize.org/news/xprize-launches-hackathon-with-2-million-prize-pool-backed-by-google) on the keynote stage: $2 million in prizes for 90 days of building real businesses on Gemini. The agent ecosystem is no longer a single venue. It is a global circuit running quarterly, and the builders who win it twice are about to define the next twelve months.',
      'Part 2 of this series covers the I/O after-hours circuit — two nights with Google DeepMind in San Francisco where the strategic signal lived between the demos. If you are a Fortune 500 leader deciding what to do with Omni, Antigravity, and the new Managed Agents API, this is the question Enso Labs is built to answer with you. [Get in touch](/contact).',
    ],
  },
  {
    slug: 'google-io-after-hours-deepmind-strategy-signal',
    title: 'Google I/O After-Hours: Two Nights With Google DeepMind and the Strategic Signal Behind the Demos.',
    dek: 'The Google I/O 2026 keynote announced Gemini Omni, Antigravity 2.0, the Managed Agents API, and Gemini 3.5 Flash. But the keynote is where the marketing lives. The after-hours is where the strategy gets decided. Two nights in San Francisco — Google for Startups × DeepMind on Tuesday, Cerebral Valley × DeepMind at Corgi Cafe on Friday. Part 2 of a two-part series.',
    pillar: 'Consult',
    date: '2026-05-26',
    readingMinutes: 7,
    tags: ['Google I/O', 'Google DeepMind', 'Cerebral Valley', 'AI Strategy', 'Gemini Omni', 'Antigravity 2.0', 'Managed Agents', 'Pomelli', 'Stitch', 'Fortune 500', 'AI Transformation', 'Thought Leadership'],
    body: [
      'The Google I/O 2026 keynote announced Gemini Omni, Antigravity 2.0, the Managed Agents API, and Gemini 3.5 Flash. But the keynote is where the marketing lives. The after-hours is where the strategy gets decided.',
      'Over the same week, I attended two of those rooms — the official **Google for Startups × Google DeepMind** reception on Tuesday May 19, and the **Cerebral Valley × DeepMind** closeout at Corgi Cafe on Friday May 22. Two nights, two crowds, two different signals from the same launch. Part 2 of a two-part series on Google I/O 2026 — [Part 1 covers the Cerebral Valley × Google I/O Hackathon featuring 3rd-place winner Yves Hughes →](/insights/google-io-hackathon-managed-agents-omni-antigravity).',
      '![Google I/O After Hours — Googler check-in and Guest check-in, the official Google for Startups × DeepMind reception, San Francisco](/images/insights/google-io-afterhours-05.jpg)',
      '## Night One: Google for Startups × Google DeepMind, Tuesday May 19',
      'The official Tuesday reception was the largest of the I/O week. The crowd was a curated mix of founders, investors, and Googlers, brought together by Google for Startups in partnership with the Google DeepMind team. The agenda was deceptively simple: ambient music, conversation, and walk-up demos of the products that had landed in the keynote earlier that day.',
      'The product booths told the actual story Google wanted to be told. **[Pomelli](https://blog.google/innovation-and-ai/models-and-research/google-labs/pomelli-agentic-capabilities/)** — Google Labs\' AI brand-builder, newly upgraded with Gemini 3.5 Flash and deeper Antigravity 2.0 integration — was running brand books and full websites end-to-end in front of the audience. **Stitch** — Google\'s real-time AI design tool now built on a streaming generation model with multiplayer canvas editing — was being demoed continuously by the team that built it. **Gemini Live** and **Gemini Robotics ER 1.5** had a third station for the embodied-AI conversations.',
      '![Google Labs activations at the I/O 2026 After Hours — Pomelli, Stitch, and the Gemini Live / Robotics ER 1.5 demo wall](/images/insights/google-io-afterhours-01.jpg)',
      'What got the most floor time in conversation was not Pomelli, not Stitch, and not the robotics work. It was **Antigravity 2.0** and **Managed Agents**. The product launches that read as "developer tooling" on the slides read very differently in a room full of founders looking at their cap tables. The implication: Google has now shipped the harness layer that historically separated platform companies from product companies. Every founder I talked to was working through the same recalculation — if Managed Agents costs less than custom infrastructure and replaces six weeks of platform engineering, where does our differentiation move next?',
      '![Daytime atrium reception — Google for Startups × Google DeepMind After Hours, San Francisco](/images/insights/google-io-afterhours-02.jpg)',
      '## Night Two: Cerebral Valley × Google DeepMind at Corgi Cafe, Friday May 22',
      'By Friday evening the I/O launch energy had compressed. The Corgi Cafe gathering was [hosted by Cerebral Valley with the Google DeepMind team](https://luma.com/deepmind) — smaller, more technical, more research-adjacent. Where the Tuesday reception was about the product launches, the Friday closeout was about what comes next.',
      'The conversations were noticeably more candid. DeepMind researchers were not in keynote mode. They were in debrief mode. The launches that had read as polished on Monday were now being discussed with the actual rough edges named — where Omni\'s physics simulation still degrades, where Antigravity 2.0\'s manager-agent loop still over-orchestrates simple tasks, where the Managed Agents harness performs differently than the live demos suggested.',
      '![Entry to the Cerebral Valley × Google DeepMind closeout — Corgi Cafe, San Francisco, Friday May 22](/images/insights/google-io-afterhours-03.jpg)',
      'The candor matters. If you only read the press coverage, you get the surface narrative. If you are in the room when the people who built the system describe what they wish they had shipped differently, you get the real product roadmap six months earlier than the next public announcement. Friday was that room.',
      '![Lounge conversations at the Cerebral Valley × Google DeepMind Post-I/O closeout — Corgi Cafe](/images/insights/google-io-afterhours-04.jpg)',
      '## Three Strategic Signals From the Two Rooms',
      'Three signals were consistent across both nights. These are the patterns I am taking into Fortune 500 client conversations this quarter.',
      '**Google is betting the company on agentic, not chat.** Omni plus Antigravity plus Managed Agents is a coherent agent-first strategy, not a model release. This is structurally different from OpenAI\'s chat-and-API motion. For enterprise transformation leaders, this matters — Google now has the platform depth to be a credible primary vendor for an agent-first transformation program, not just a model vendor inside a multi-vendor stack.',
      '**DeepMind is now Google\'s product team, not Google\'s research lab.** Three years ago DeepMind shipped papers. Today DeepMind shipped the keynote. Varun Mohan demoed Antigravity building an operating system live on stage. Multiple DeepMind staffers ran the product booths Tuesday night and the debrief Friday night. The org chart shift is the strategy shift. Anyone evaluating Google Cloud\'s enterprise AI roadmap should re-weight DeepMind heavily in the credibility math.',
      '**Cerebral Valley is the new accelerator class.** Not Y Combinator. Not a16z. Not Sequoia Scout. A community of model labs plus curated builders plus curated capital — running a quarterly hackathon circuit that is rapidly becoming the highest-signal builder events of the year. The Paris July events ([RAISE Summit](https://raisesummit.com/) July 4-5, Machina Hackathon July 6) confirm this is a global motion. For founders and corporate development teams trying to get inside the next launch cycle of a frontier model, the Cerebral Valley calendar is now table stakes.',
      '## What Comes Next',
      'Three product cycles to watch over the next two quarters. **Antigravity 2.5** — the multi-agent orchestration is shipping fast enough that another release inside calendar 2026 is realistic; the next version will likely formalize agent-to-agent communication primitives that did not make 2.0. **Omni 2** — DeepMind\'s roadmap on world models is more ambitious than what shipped on Monday; the interactive use cases (robotics simulation, real-time physics) are a bigger story than video generation. **The [Build with Gemini XPRIZE](https://www.xprize.org/news/xprize-launches-hackathon-with-2-million-prize-pool-backed-by-google)** — Google\'s $2 million, 90-day hackathon competition announced on the I/O stage closes in Q3, and the winning projects will define what a "production agentic business" looks like at Google scale.',
      '## For C-Suite Leaders Reading This',
      'If you have not already initiated a Google Cloud relationship conversation around the I/O 2026 stack, the next thirty days are the moment. Google\'s GTM team is in full follow-up motion right now — I received outreach from Google Cloud titled "From Next \'26 to Production: Let\'s connect" within forty-eight hours of returning from San Francisco. The combination of Managed Agents (commodity), Antigravity 2.0 (differentiation), and Omni (long bet) is the exact mix that warrants a structured Q3 evaluation against your existing Anthropic and OpenAI footprints.',
      'Part 1 of this series covers the Cerebral Valley × Google I/O Hackathon and features 3rd-place winner Yves Hughes. [Read Part 1 →](/insights/google-io-hackathon-managed-agents-omni-antigravity). If you are mapping a Q3 AI transformation roadmap and want a partner-tier read on Google\'s new stack — and where Anthropic and OpenAI fit alongside it — this is what Enso Labs is built to help you do. [Get in touch](/contact).',
    ],
  },
  {
    slug: 'notion-career-agent-open-source-hackathon',
    title: 'Notion Just Launched a Developer Platform. We Shipped an Open-Source Career Agent on Day One.',
    dek: 'Three days after Notion unveiled Workers, MCP, and an Agent SDK, we were at their first hackathon in San Francisco — building a career intelligence agent that anyone can fork and deploy today.',
    pillar: 'Build',
    date: '2026-05-19',
    readingMinutes: 8,
    tags: ['AI Agents', 'Notion', 'Notion Workers', 'MCP', 'Claude', 'Open Source', 'Hackathon', 'TypeScript', 'Career Intelligence', 'Agentic Systems', 'Anthropic', 'Developer Platform'],
    body: [
      'On May 13, Notion [launched a developer platform](https://www.notion.com/releases/2026-05-13) that turns every workspace into an AI agent hub — Workers for custom code, MCP for data access, an Agent SDK for external integrations, and a CLI for deployment. [TechCrunch called it](https://techcrunch.com/2026/05/13/notion-just-turned-its-workspace-into-a-hub-for-ai-agents/) a move that positions Notion as an orchestration layer where people and agents collaborate across tools and databases. Three days later, we were at Notion HQ in San Francisco for their first-ever Developer Platform Hackathon.',
      'We shipped a career intelligence agent in 24 hours — five Notion Worker tools, 487 lines of TypeScript, a full pipeline from job scanning to AI-tailored resume generation. **The project is open source and ready to fork.** [github.com/nycsav/notion-career-agent](https://github.com/nycsav/notion-career-agent)',
      '![Welcome hackers — Notion Developer Platform Hackathon, sponsored by Anthropic, Vercel, and OpenAI](/images/insights/notion-hackathon-01.jpg)',
      '## Notion\'s Developer Platform: What Launched and Why It Matters',
      'The [Notion Developer Platform](https://www.notion.com/product/developer-platform) is the biggest expansion of Notion\'s capabilities since the API launched in 2021. Over 1 million custom agents have already been built since Notion introduced AI agents in February 2026. The developer platform gives builders the primitives to go much further:',
      '**Notion Workers** are sandboxed TypeScript functions that run on Notion\'s infrastructure. No servers, no deployment pipelines — you write the logic and deploy with the Notion CLI. Workers are free during beta, with credit-based pricing starting August 11, 2026.',
      '**Notion MCP** (Model Context Protocol) servers let any AI assistant — Claude, Codex, or your own agents — read and write Notion data natively. This is the data layer that makes Notion a genuine platform, not just a workspace.',
      '**The Agent SDK and External Agents API** bring external agents into Notion as native workspace participants. At launch, partners include Claude Code, Cursor, Codex, and Decagon.',
      '**Database Sync** pulls data from any API (Salesforce, Zendesk, Postgres) directly into Notion databases — making the workspace the single pane of glass for agent workflows.',
      'For builders, the implication is clear: you can now ship AI agents that live where your users already work, backed by Anthropic, Vercel, and OpenAI as platform sponsors.',
      '![Notion Hackathon — May 16-17, San Francisco, backed by Anthropic, Vercel, and OpenAI](/images/insights/notion-hackathon-02.jpg)',
      '## What We Built: An Open-Source Career Intelligence Agent',
      'Job seekers submit an average of 16 applications per week but spend less than 30 minutes customizing each one. Tailored resumes are 61% more likely to land interviews, but deep customization does not scale with manual effort. The existing tools are either spam cannons (mass-apply bots that tank your response rate) or glorified spreadsheets. We built a system that does the intelligence work — scanning, scoring, tailoring — while keeping the human in the loop for every decision that matters.',
      '## Five Notion Worker Tools, One Pipeline',
      'The career agent runs entirely inside a Notion workspace using Notion Workers — the same runtime powering Notion AI agents across the platform. No servers to manage, no infra to maintain. We built five Agent Tools that chain together into an end-to-end career pipeline:',
      '**scanJobs** parses job listings from LinkedIn email notifications, extracts structured data (title, company, location, salary, requirements), and scores each role against the user\'s career profile using Claude Haiku. Every job gets a match score from 0 to 100 with a written rationale. Jobs scoring 75+ get flagged for action.',
      '**tailorResume** is the heavy lifter. Give it a job listing and a base resume, and it generates an ATS-optimized resume and cover letter using Claude Sonnet — the stronger model, because resume quality directly affects interview conversion. It extracts ATS keywords from the listing, maps them against existing experience, and returns structured data ready to save as linked Notion pages.',
      '**getCareerInsight** turns the agent into a strategic career advisor. Salary negotiation data, interview prep, company research — direct and actionable, powered by Haiku for speed on quick Q&A.',
      '**configureAgent** lets the user set automation preferences: copilot (suggestions only), autopilot (acts with confirmation), or autonomous (full auto). You configure scan cadence, match threshold, target roles, locations, salary minimum, and notification channels. The agent adapts its behavior to your risk tolerance.',
      '**getAgentStatus** provides pipeline analytics — jobs scanned, scored, applied, interviewing, offered, rejected — filtered by time range. The control panel for knowing whether your job search machine is working.',
      '![The hackathon space at Notion HQ, Annie Street, San Francisco](/images/insights/notion-hackathon-03.jpg)',
      '## Two-Model Architecture: Matching Claude to Task Criticality',
      'We deliberately split the AI work across two Claude models — a pattern we call task-criticality routing. Haiku (claude-haiku-4-5) handles the high-volume, speed-sensitive operations: job scoring, career Q&A, classification. Sonnet handles the high-stakes generation: resume tailoring and cover letters where quality directly drives outcomes.',
      'This is not about cost optimization. It is about matching model capability to task criticality. A wrong match score wastes a click. A weak resume wastes an interview opportunity. The same two-model pattern applies to any Notion AI agent where you need both throughput and quality — customer support triage versus response drafting, lead scoring versus proposal generation.',
      '## Source-Tier Ranking: Not All Applications Are Equal',
      'We ported the source-tier ranking system from [signal2noise](https://signals.ensolabs.ai), our market intelligence platform, into the career agent. Every job is classified by acquisition channel: Tier 1 (direct referral, ~50% interview rate) through Tier 5 (cold apply, ~2%). This changes the agent\'s behavior — a Tier 1 referral with a 60 match score still gets priority over a Tier 5 cold apply at 85.',
      'The system encodes what experienced job seekers already know intuitively: **who referred you matters more than how perfectly your resume matches.** Source-tier ranking is a general pattern — it applies equally to sales pipelines, content distribution, and investor outreach.',
      '![Building and presenting at the Notion Developer Platform Hackathon](/images/insights/notion-hackathon-05.jpg)',
      '## Building on Notion Workers: What We Learned',
      'Three observations from shipping Notion AI agents in production during the hackathon:',
      '**Speed to deployment is real.** We went from zero to five deployed Notion Worker tools in under 24 hours using Claude Code as the primary dev environment. The Notion CLI (`npx notion workers deploy`) handles packaging and deployment. The Notion SDK provides typed access to databases, pages, and blocks. The developer experience is the best we have seen for agent deployment.',
      '**Notion MCP changes the integration model.** With [Notion MCP](https://www.notion.com/product/developer-platform), any MCP-compatible AI assistant — Claude, Codex, your own agents — can read and write Notion data natively. The career agent stores every job, resume, and status update as structured Notion pages. That data is immediately accessible to any other Notion AI agent or MCP client without additional integration work.',
      '**The design patterns transfer.** We have been running signal2noise on Firebase and Vercel for months. Porting its intelligence patterns (source-tier ranking, multi-model routing, structured output parsing) to Notion Workers took hours, not weeks. If you have built agentic systems on any modern runtime, you can build Notion AI agents.',
      '## Fork It, Ship It, Make It Yours',
      'The career agent is open source and ready to deploy. Fork the repo, plug in your own resume and career preferences, and you have a working career intelligence system inside your Notion workspace. The architecture patterns — multi-model routing, source-tier ranking, configurable automation levels — are designed to be portable to any domain.',
      '[Fork on GitHub →](https://github.com/nycsav/notion-career-agent)',
      '## What This Means for the Notion Ecosystem',
      'Notion\'s Developer Platform is the most significant expansion of a productivity tool into an AI agent runtime we have seen. With 1 million custom agents already built, Workers free through August, and partners like Anthropic and OpenAI backing the ecosystem, this is a genuine platform play — not a feature announcement.',
      'The workspace is the interface. The Worker is the runtime. Notion MCP is the data layer. For builders and enterprises evaluating where to ship their next AI agent, Notion just became a serious platform option.',
      'At Enso Labs, we build AI agents on Notion and every major platform. The career agent is a compressed case study of how we approach every engagement: decompose the workflow, insert AI where it creates the most leverage, keep humans in the loop where judgment matters. If you are evaluating Notion Workers for your team, [get in touch](/contact).',
    ],
  },
  {
    slug: 'why-deck-only-ai-consulting-fails-production',
    title: 'Why deck-only AI consulting dies on contact with production.',
    dek: 'The gap between a beautiful slide and a running system is where most enterprise AI initiatives quietly die. Here\'s the autopsy from fifteen years inside the room.',
    pillar: 'Consult',
    date: '2026-04-22',
    dateModified: '2026-05-26',
    readingMinutes: 7,
    tags: ['AI Consulting', 'Strategy-to-Ship', 'Enterprise AI', 'Production AI', 'AI Transformation'],
    body: [
      'Most AI consultancies have a wildly successful first ninety days. The deck lands. The roadmap is celebrated. The exec sponsor commits. Then the engagement ends — and the system never ships.',
      'The reason is structural, not motivational. A deck-only consultancy hands off the architecture to an internal team that never participated in the design, then walks away from the production realities — eval harnesses, governance, latency budgets, hallucination guardrails — that determine whether the thing actually runs.',
      'The fix is not better decks. The fix is **the same operator who designs the system also ships it.** That collapses the translation layer. Architecture decisions get made by the person who has to debug them at 2am.',
      'This is why the Strategy-to-Ship Framework is sequenced the way it is: Diagnose, Design, Build, Scale — with the same builder across every phase. The roadmap and the runtime are the same artifact.',
    ],
  },
  {
    slug: 'gore-lens-expert-knowledge-encoding',
    title: 'The Gore Lens: encoding expert knowledge as toggleable rules.',
    dek: 'A scientist will never trust a black-box relevance score. Here\'s how we built a 9-rule expert lens that scientists could reason about — and turn off — one rule at a time.',
    pillar: 'Build',
    date: '2026-04-15',
    dateModified: '2026-05-26',
    readingMinutes: 9,
    tags: ['AI Agents', 'Expert Systems', 'MCP', 'Market Intelligence', 'Enterprise AI', 'Fortune 500'],
    body: [
      'The Gore M2 Intelligence Hub had one non-negotiable acceptance criterion: the lead scientist had to trust the relevance ranking. That meant no opaque embeddings-as-relevance, no LLM-as-judge with hidden criteria, no statistical magic.',
      'What worked: encoding the scientist\'s actual decision criteria as nine explicit, MCP-compatible rules. Temperature floor. Material class. Chemistry scope. PFAS sensitivity. Market size. Liability exposure. Recency. Novelty. The 200°C gap.',
      'Each rule is independently toggleable. The dashboard shows the score with the rule on and off. The scientist can A/B their own expertise against the system. That\'s where trust comes from — not from the score, but from the ability to interrogate it.',
      'The pattern generalizes: **wherever you need expert trust, encode the expert\'s heuristics explicitly, and make every one of them inspectable.**',
    ],
  },
  {
    slug: 'mcp-servers-new-saas-integration',
    title: 'MCP servers are the new SaaS integration layer.',
    dek: 'Every legacy SaaS connector — Salesforce, Slack, Notion, Looker — gets a second life as an MCP server. The companies that ship MCP first will own the agent-native enterprise.',
    pillar: 'Build',
    date: '2026-04-08',
    dateModified: '2026-05-26',
    readingMinutes: 6,
    tags: ['MCP', 'Model Context Protocol', 'SaaS', 'AI Agents', 'Enterprise Integration', 'Claude', 'Agentic Systems'],
    body: [
      'For two decades, enterprise software lived inside a tab. The unit of work was the screen. Integration meant Zapier, REST, or a poorly-maintained iPaaS connector.',
      'The Model Context Protocol changes the unit. The unit is now the tool call. An MCP server publishes a typed surface that any agent — Claude, Perplexity Computer, Gemini — can invoke autonomously, with structured input and structured output.',
      'The implication for B2B SaaS: every connector you have today should be reframed as an MCP server. The buyer will ask for it within twelve months. The companies that ship first own the agent-native distribution layer for the next decade.',
      'We build these. They are usually two- to six-week engagements, depending on auth complexity and surface area.',
    ],
  },
  {
    slug: 'rag-eval-harness-not-vector-store',
    title: 'Your RAG problem is an eval problem, not a vector-store problem.',
    dek: 'Teams burn months optimizing chunk sizes, hybrid retrieval, and reranker stacks. Then they ship — and discover they never had a reliable way to know if the answer was right.',
    pillar: 'Build',
    date: '2026-04-01',
    dateModified: '2026-05-26',
    readingMinutes: 8,
    tags: ['RAG', 'Eval Harness', 'LLM', 'Production AI', 'Vector Search', 'AI Architecture'],
    body: [
      'Most RAG systems we are asked to rescue have a sophisticated retrieval pipeline and a non-existent eval harness. The team can describe their reranker but cannot tell you the F1 on a held-out set of expert-graded answers.',
      'This is backwards. The eval harness is the spec. Without it, every change is a vibes-based experiment — chunk size up, chunk size down, embedding model swap, hybrid weight knob — with no way to know if you are getting better or worse.',
      'Build the eval first. Hand-grade fifty representative queries with expert ground truth. Score every change against that set. The retrieval architecture you end up with will be different — and shippable.',
    ],
  },
  {
    slug: 'autonomous-trading-risk-as-architecture',
    title: 'In autonomous trading, the kill-switch is the architecture.',
    dek: 'The Trading Terminal runs unattended. That is only possible because the risk caps, position sizing, and shut-off logic were designed before the alpha logic — not after.',
    pillar: 'Ship',
    date: '2026-03-25',
    dateModified: '2026-05-22',
    readingMinutes: 10,
    tags: ['Financial AI', 'Trading', 'Autonomous Systems', 'Risk Architecture', 'Enso Trading Terminal', 'AI Agents'],
    body: [
      'Most trading systems begin with the strategy: a signal, an indicator, an alpha. The risk layer arrives later, bolted on, and is the first thing to fail under stress.',
      'The Enso Trading Terminal was built backwards on purpose. The kill-switch came first. Risk caps were schemas, not config. Position sizing was a typed function with property tests, not a magic number in a YAML file.',
      'The result is a system that can run unattended without anyone losing sleep. Strategy code can be wrong. Risk code cannot.',
      'For client engagements building autonomous trading, the rule is the same: the risk surface is the architecture. Strategy is a plug-in.',
    ],
  },
  {
    slug: 'ai-coe-pharma-mlr-compliance',
    title: 'An AI Center of Excellence that ships MLR-compliant work.',
    dek: 'Pharma agencies cannot move fast and break things. Medical, Legal, and Regulatory review is non-negotiable. Here\'s how we built a CoE that compresses launches from three months to two weeks anyway.',
    pillar: 'Consult',
    date: '2026-03-18',
    dateModified: '2026-05-22',
    readingMinutes: 7,
    tags: ['Pharma AI', 'AI Center of Excellence', 'Compliance', 'MLR', 'Healthcare AI', 'Enterprise AI', 'AI Transformation'],
    body: [
      'The standard objection to AI in pharma marketing is compliance. MLR/PRC review, FDA fair balance, brand voice tolerance — every shortcut breaks one of them.',
      'The Heller Center of Excellence was designed around the constraint, not despite it. RAG retrieval is grounded in five brand knowledge bases that already encode MLR-approved language. Pre-flight scans run on every draft. The compliance burden is automated, not bypassed.',
      'The metric that matters: campaign launches dropped from three months to two weeks. Compliance review time barely moved — what compressed was everything before it.',
      'The lesson: regulated industries are not where AI fails. They are where it has the largest leverage, **if you treat compliance as the spec rather than the obstacle.**',
    ],
  },
  {
    slug: 'options-flow-decision-support-not-black-box',
    title: 'Options flow analytics: decision support, not black box.',
    dek: 'Unusual flow is a hypothesis, not a trade. The Options Lab is built to surface hypotheses, force the human to vet them, and only then route to execution.',
    pillar: 'Ship',
    date: '2026-03-11',
    dateModified: '2026-05-22',
    readingMinutes: 5,
    tags: ['Financial AI', 'Options Trading', 'Decision Support', 'Human-in-the-Loop', 'Trading Terminal'],
    body: [
      'The marketing of "AI-powered options flow" usually implies an oracle — feed it tickers, get trades. That is exactly the model that loses money.',
      'The Options Lab is a decision-support tool. It surfaces unusual flow, sweeps, and blocks; cross-references against the news intelligence feed and the implied volatility surface; and presents the operator with a vetting checklist before any execution route is enabled.',
      'The human is in the loop on purpose. The system is good at finding hypotheses. It is the operator\'s job to kill the bad ones — and the operator should have to actively click "send" on every one that survives.',
    ],
  },
  {
    slug: 'principal-led-vs-50-person-consultancy',
    title: 'A principal-led studio outperforms a 50-person consultancy on shipped systems.',
    dek: 'Counterintuitive — and structural, not heroic. Six things change when the advisor and the build team work as one unit.',
    pillar: 'Consult',
    date: '2026-03-04',
    dateModified: '2026-05-22',
    readingMinutes: 6,
    tags: ['AI Consulting', 'Boutique Studio', 'Strategy-to-Ship', 'Principal-Led', 'Enterprise AI'],
    body: [
      'The pitch from a 50-person consultancy is depth of bench. The reality is hand-offs. Strategy decided in week 3 reaches engineering in week 9, refracted through three layers of partial context.',
      'A principal-led studio has structural advantages a large bench cannot replicate. Direct senior access — no account managers. Builder credibility — the advisor is also in the codebase. Dogfooding — the studio runs its own infrastructure. Speed — no approval chain. Selectivity — a fixed pipeline forces a yes to mean yes.',
      'The constraint is also real: bandwidth. A principal-led studio runs a small handful of deep engagements at a time. That is the whole point — depth, not portfolio. When the studio is at capacity, prospects hear so directly and get a future date.',
    ],
  },
  {
    slug: 'anthropic-financial-services-what-it-means',
    title: 'Anthropic Just Launched 10 Financial AI Agents. We Built Ours Last Year.',
    dek: 'Today Anthropic announced pre-built AI agents for banking and trading — pitchbook builders, credit memo drafters, statement auditors. Enso Labs has been shipping production financial agents since 2025. Here is what this means for the industry and why early movers have a structural advantage.',
    pillar: 'Ship',
    date: '2026-05-05',
    dateModified: '2026-05-28',
    readingMinutes: 6,
    tags: ['Financial AI', 'Anthropic', 'Claude', 'AI Agents', 'Trading', 'MCP', 'Enso Trading Terminal'],
    body: [
      'On May 5, 2026, Anthropic announced ten pre-built AI agents for financial services — pitchbook builders, credit memo drafters, portfolio summarizers, statement auditors. The announcement validates what we have been building at Enso Labs since 2025: production financial AI agents are not a research project. They are an operational layer.',
      'The Enso Trading Terminal has been running autonomously in production for over a year — news-driven trading algorithms, multi-agent research automation, options flow analysis, brokerage API integration via MCP. When Anthropic says Claude can now draft credit memos and audit financial statements, we hear confirmation of a thesis we have already shipped against: **the same reasoning engine that writes prose can manage risk, parse filings, and route orders.**',
      'What makes the Anthropic launch significant is not the agents themselves — it is the infrastructure underneath. Claude\'s financial services stack now includes MCP-connected brokerage APIs, compliance-aware reasoning, and audit-trail generation built into the model layer. This collapses the integration burden. A year ago, building a compliant trading agent meant wiring together four vendors. Now it means configuring one.',
      'The implication for enterprises: the window to build proprietary financial AI agents — and own the operational advantage — is compressing. The pre-built agents will commoditize the basics (memo drafting, statement reconciliation, portfolio summarization). The moat is in what you build on top: custom signal intelligence, firm-specific risk models, compliance layers tuned to your regulatory surface.',
      'Early movers have a structural advantage. The firms that shipped financial agents in 2025 — including our own terminal — have twelve months of production data, eval harnesses, and operational muscle that a cold start in 2026 cannot replicate. The question is no longer whether to build financial AI agents. It is whether you want to be the firm that built early or the firm that bought late.',
      'We build these systems. If you are a bank, asset manager, or fintech evaluating Claude\'s financial services stack, we can show you what a production deployment looks like — because we have been running one.',
    ],
  },
  {
    slug: 'mcp-brokerage-trading-model-context-protocol',
    title: 'MCP for Brokerage: How Model Context Protocol Is Connecting AI to Trading.',
    dek: 'Every brokerage API — Alpaca, Interactive Brokers, Schwab, TradeStation — is becoming an MCP server. This is the integration pattern that makes autonomous financial AI agents practical.',
    pillar: 'Build',
    date: '2026-05-08',
    dateModified: '2026-05-28',
    readingMinutes: 8,
    tags: ['MCP', 'Model Context Protocol', 'Brokerage', 'Financial AI', 'Trading', 'AI Agents', 'Alpaca', 'Interactive Brokers'],
    body: [
      'The Model Context Protocol is the most consequential piece of AI infrastructure that almost no one in financial services is talking about. MCP is a standardized way for AI agents — Claude, Gemini, GPT — to invoke external tools with typed inputs and structured outputs. For trading, that means a single agent can check positions, submit orders, retrieve account data, and monitor fills as part of its reasoning loop.',
      'Before MCP, connecting an AI agent to a brokerage meant building a bespoke integration for every API. Alpaca REST endpoints, Interactive Brokers TWS, Schwab\'s OAuth2 flow, TradeStation\'s streaming WebSocket — each required custom auth, custom error handling, and custom response parsing. The result was fragile plumbing that broke every time a vendor updated their API.',
      'MCP collapses this. An MCP server wraps a brokerage API into a typed tool surface — function name, input schema, output schema — that any MCP-compatible agent can invoke natively. The agent does not need to know whether it is talking to Alpaca or Interactive Brokers. It calls `submit_order` with a typed payload and gets a typed response. The integration complexity lives in the server, not the agent.',
      'The architecture looks like this: the AI agent runs a reasoning loop — read breaking news, analyze the options chain, check the restricted list, calculate position sizing. When it decides to act, it calls an MCP tool. The MCP server validates the request against pre-trade risk controls (position limits, notional limits, order rate limits), then forwards it to the brokerage API. Every tool call is logged with inputs, outputs, timestamps, and the full reasoning context. That is the audit trail.',
      'We have been running this pattern in production since 2025. The Enso Trading Terminal connects to Alpaca, Public.com, and crypto exchanges via MCP servers that we built and maintain. The agent reads a news article about an FDA approval, checks the options chain for the relevant ticker, verifies risk limits, calculates sizing, and submits — all in one agentic loop. The entire flow is logged and reviewable.',
      'The practical implication for financial institutions: **MCP is the new SaaS integration layer for finance.** Every brokerage, market data provider, and compliance system should be evaluating how to publish an MCP surface. The firms that ship MCP servers first will own the distribution layer for the next generation of AI-native trading infrastructure. We build these servers. They are usually two- to six-week engagements.',
    ],
  },
  {
    slug: 'claude-partner-network-boutique-implementation',
    title: 'Why Boutique Firms Are the Right Claude Implementation Partner.',
    dek: 'Anthropic launched a $100M Claude Partner Network. Accenture, Deloitte, and PwC are in. But for production agentic systems, the structural advantages belong to boutique operators who build what they advise.',
    pillar: 'Consult',
    date: '2026-05-07',
    dateModified: '2026-05-28',
    readingMinutes: 7,
    tags: ['Claude', 'Anthropic', 'AI Consulting', 'Partner Network', 'Boutique Studio', 'Enterprise AI', 'Agentic Systems'],
    body: [
      'Anthropic\'s Claude Partner Network — backed by $100 million in funding — is designed to accelerate enterprise Claude deployments through certified implementation partners. The launch partners include the usual suspects: Accenture, Deloitte, PwC, McKinsey, BCG. The pitch is depth of bench and global reach.',
      'The reality is different. Enterprise Claude deployments are not ERP migrations. They are not lift-and-shift projects that benefit from armies of consultants following a playbook. Agentic AI systems require the person who designed the architecture to also debug the eval harness at 2am. They require the advisor to be in the codebase. The hand-off model that works for SAP does not work for Claude.',
      'Boutique firms have structural advantages in this market. **First: direct senior access.** No account managers, no project coordinators, no layers between the client and the person who understands the system. The principal who scopes the engagement is the same person who writes the MCP server and tunes the eval suite. **Second: builder credibility.** The studio runs its own production AI infrastructure — the Enso Trading Terminal, signal2noise, MCP servers in live environments. When we advise on architecture, we are describing systems we operate.',
      '**Third: speed.** A 50-person consultancy needs three weeks to staff a project. A boutique deploys a working prototype in the same three weeks. **Fourth: dogfooding.** We use Claude to build our own products, run our own analytics, and manage our own operations. Every recommendation we make has been tested on ourselves first.',
      'The Claude Partner Network is good for the ecosystem. It validates enterprise demand and creates a certification layer that helps buyers evaluate partners. But certification is a floor, not a ceiling. The partners who will win production deployments are the ones who can point to shipped systems — not the ones with the largest partner tier.',
      'Enso Labs is a principal-led AI transformation studio. We are Claude-certified, Anthropic-credentialed, and running Claude-powered production systems across financial services, healthcare, and B2B technology. If you are evaluating Claude implementation partners, ask one question: **show me the system you shipped.** That is the only credential that matters.',
    ],
  },
];

export const insightsByPillar = (pillar?: Pillar) =>
  pillar ? INSIGHTS.filter((i) => i.pillar === pillar) : INSIGHTS;

export const getInsight = (slug: string) =>
  INSIGHTS.find((i) => i.slug === slug);
