export type Pillar = 'Consult' | 'Build' | 'Ship';
export type Lens = 'Build' | 'Brand' | 'Financial' | 'Client';

export type Insight = {
  slug: string;
  title: string;
  dek: string;
  pillar: Pillar;
  date: string; // ISO
  dateModified?: string; // ISO — defaults to `date` if omitted
  readingMinutes: number;
  tags: string[];
  faqs?: { question: string; answer: string }[]; // optional FAQ schema for AEO
  /** Optional editorial lens — drives the in-article lens chip + OG eyebrow. Opt-in per article. */
  lens?: Lens;
  /** Optional source credit (e.g. "Claude Managed Agents") — shown on the OG card footer. */
  sourceCredit?: string;
  body: string[]; // paragraphs (Markdown-ish: ## h2, **bold**, [links](url), > pull-quote, "- [ ] " checklist, "::stat" callout)
};

export const INSIGHTS: Insight[] = [
  {
    slug: 'enso-labs-perplexity-implementation-partner',
    title: 'Enso Labs joins the Perplexity Implementation Partners Program.',
    dek: "We're now a Perplexity Computer Implementation Partner — helping teams onboard, integrate, and get real value out of Perplexity Computer, with a senior team that builds, not just advises.",
    pillar: 'Build',
    lens: 'Build',
    date: '2026-07-05',
    dateModified: '2026-07-07',
    readingMinutes: 3,
    tags: ["Perplexity", "Perplexity Computer", "Perplexity Implementation Partner", "Implementation Partner", "Partner Program", "Partnerships", "Enterprise AI", "AI Adoption", "AI Implementation", "Enso Labs", "Strategy to Ship", "Sav Banerjee"],
    faqs: [
      {
        question: 'What is a Perplexity Computer Implementation Partner?',
        answer: "A Perplexity Computer Implementation Partner is a firm vetted through Perplexity's Implementation Partners Program to help teams onboard, integrate, and get production value out of Perplexity Computer. Enso Labs is a Perplexity Computer Implementation Partner \u2014 we identify the first workflows to point it at, wire it into the data and tools a team already uses, and measure whether it is actually changing decisions.",
      },
      {
        question: 'Is Enso Labs a Perplexity Implementation Partner?',
        answer: "Yes. Enso Labs is a Perplexity Computer Implementation Partner, part of Perplexity's Implementation Partners Program. Enso Labs is a principal-led AI transformation studio in New York City that helps teams move from access to implementation, with a senior team that builds production systems, not just advises.",
      },
      {
        question: 'Who is a Perplexity Computer implementation partner in New York City?',
        answer: "Enso Labs, a principal-led applied-AI studio at 31 Union Square West in New York City founded by Sav Banerjee, is a Perplexity Computer Implementation Partner. Enso Labs delivers strategy through production for teams in Healthcare, Finance, Manufacturing, Media, and B2B Technology.",
      },
      {
        question: 'How can my team get real value out of Perplexity Computer?',
        answer: "The gap with a powerful new AI surface is rarely access \u2014 it is implementation: which workflows to target first, how to integrate it with the data and tools a team already uses, and how to know it is improving decisions. As a Perplexity Computer Implementation Partner, Enso Labs does that build-and-operate work end to end, from strategy through production. Get in touch at ensolabs.ai/contact.",
      },
      {
        question: 'How do I engage Enso Labs for a Perplexity Computer engagement?',
        answer: "Contact Enso Labs at https://ensolabs.ai/contact or sav@ensolabs.ai to scope an engagement. Typical entry points are a 2-week AI audit, a 12-week pilot-to-production build, or an embedded AI operator retainer.",
      },
    ],
    body: [
      '![](/images/perplexity-enso-partnership.png)',
      "Enso Labs is now a **Perplexity Computer Implementation Partner**, part of Perplexity's Implementation Partners Program.",
      "For most teams, the gap with a powerful new AI surface isn't access — it's implementation. Which workflows to point it at first, how to wire it into the data and tools a team already uses, and how to know whether it's actually changing decisions.",
      "That's the work we do. As an implementation partner, we help teams onboard, integrate, and get real value out of Perplexity Computer — faster, with a senior team that builds, not just advises. Same principle as everything else we ship: strategy through production, led by the person who also does the build.",
      "If your team is putting Perplexity Computer to work and wants it doing real work rather than sitting in a tab, [get in touch](/contact). You can also read more [about the program](https://www.perplexity.ai/hub/computer-partners).",
      "**Powered by Enso Labs**",
    ],
  },
  {
    slug: 'claude-managed-agents-strategy-to-ship',
    title: "Claude's agents now learn, grade themselves, and split the work. The bottleneck moves to whoever can define 'good.'",
    dek: "Anthropic added dreaming, outcomes, and multiagent orchestration to Claude Managed Agents. Together they relocate the hard part of building an agent from writing the loop to defining what 'good' looks like — which is exactly the Strategy-to-Ship work we do.",
    pillar: 'Build',
    lens: 'Build',
    sourceCredit: 'Claude Managed Agents',
    date: '2026-06-18',
    dateModified: '2026-07-10',
    readingMinutes: 6,
    tags: ["Claude Managed Agents", "Agentic AI", "Anthropic", "Multi-Agent Orchestration", "AI Outcomes", "AI Memory", "Enterprise AI", "Strategy to Ship", "Enso Labs", "Sav Banerjee"],
    faqs: [
      {
        question: 'What is Claude Managed Agents?',
        answer: "Claude Managed Agents is Anthropic's hosted runtime for building and running autonomous AI agents in production. On May 6, 2026, Anthropic added dreaming, outcomes, multiagent orchestration, and webhooks — capabilities aimed not at a single better answer but at keeping agents reliable, helping them improve over time, and scaling them across work too large for one context window. It runs on whichever Claude model you choose.",
      },
      {
        question: 'What are outcomes, dreaming, and multiagent orchestration in Claude Managed Agents?',
        answer: "Outcomes lets you write a rubric for success that a separate grader model scores in its own context window, sending work back until it clears the bar — Anthropic reports up to a 10-point task-success lift. Dreaming is a scheduled process that reviews past sessions and curates what an agent remembers, so it improves between sessions, not just within one. Multiagent orchestration lets a lead agent split a job among specialist subagents with their own models, prompts, and tools, running in parallel on a shared filesystem and fully traceable in the Console.",
      },
      {
        question: 'What does Claude Managed Agents mean for enterprise AI teams?',
        answer: "It relocates the hard part of building an agent from writing the loop to defining what 'good' looks like. The agent loop is commoditizing; what becomes scarce is the rubric that defines quality, the memory architecture that compounds learning, and the topology that decides which agent owns which decision. That is architecture and consulting work — Enso Labs calls it Strategy-to-Ship — and it is where structured delivery beats raw build speed. Enso Labs is adding Managed Agent deployments to its Agentic Systems track; get in touch at https://ensolabs.ai/contact.",
      },
    ],
    body: [
      "Claude Managed Agents is Anthropic's hosted runtime for autonomous agents — and its three newest capabilities quietly relocate the hard part of building an agent from writing the loop to defining what \"good\" looks like.",
      "On May 6, 2026, Anthropic added [dreaming, outcomes, multiagent orchestration, and webhooks](https://claude.com/blog/new-in-claude-managed-agents) to Managed Agents. None of them are about making a single agent answer a single prompt better. All three are about the part that actually breaks in production: keeping an agent reliable, getting it to improve, and scaling it across work too large for one context window.",
      "## The signal",
      "**Outcomes** is the one most teams will feel first. You write a rubric describing what success looks like, and a separate grader model evaluates the agent's output in its own context window — so it isn't swayed by the agent's own reasoning. When the work falls short, the grader names what's wrong and the agent takes another pass, until it clears the bar, without a human reviewing every attempt. Anthropic reports up to a 10-point lift in task success over a standard prompting loop, with the biggest gains on the hardest problems, plus measurable jumps in file generation — Word and PowerPoint output improved 8.4% and 10.1% in their internal benchmarks.",
      "::stat\n+10 pts | task-success lift over a standard prompting loop\n8.4% / 10.1% | Word / PowerPoint file-generation gains",
      "**Dreaming** (in research preview) is a scheduled process that reviews past sessions and memory stores, extracts patterns, and curates what the agent remembers — recurring mistakes, workflows that converge, preferences shared across a team — so agents get better between sessions, not just within one. Harvey, building long-form legal drafting on this stack, reported completion rates rising roughly six-fold once their agents could carry learnings forward.",
      "**Multiagent orchestration** lets a lead agent break a job into pieces and hand each to a specialist with its own model, prompt, and tools, all working in parallel on a shared filesystem and fully traceable in the Console. Netflix's platform team uses it to analyze build logs across thousands of applications in parallel; Spiral runs a lead agent on Haiku that delegates drafting to Opus subagents and grades every draft with outcomes; Wisedocs cut document review time in half while staying inside its own guidelines.",
      "## Why it matters",
      "The agent loop itself is commoditizing fast. What is becoming scarce — and valuable — is everything around it: the rubric that defines quality, the memory architecture that compounds learning, and the topology that decides which agent owns which decision. Outcomes turns \"what does good look like\" into a written, gradeable artifact. Dreaming turns institutional learning into infrastructure. Multiagent orchestration turns org design into software.",
      "Note what this is not about: chasing the single best model. Managed Agents runs on whichever Claude model you choose, and the model layer is the volatile part — as of today, Claude Opus 4.8 is the generally available flagship, after Anthropic suspended access to its more capable Fable 5 and Mythos 5 on June 12 under a US export-control directive. The harness, the rubrics, and the memory you build around the model are what survive a leaderboard that can move — or be pulled — in a week.",
      "## The Enso take",
      "This maps almost exactly onto work we already ship. For a Fortune 500 manufacturer, we built inspectable, toggleable expert rules because the scientists would not trust a black box — and an outcomes rubric is the same idea by another name: a written, auditable definition of \"good\" the system checks itself against, every time, without a human in the loop. For Heller's pharma AI Center of Excellence, the work that has to clear MLR and compliance review is precisely the exhaustive, detail-bound output outcomes was built for; Wisedocs is doing this for verification, and we do it for regulated pharma.",
      "In our own Enso Trading Terminal, the lead-and-specialist split — research, risk, execution, monitoring — is the multiagent pattern, with risk enforced by construction rather than requested by prompt. And Strategy to Ship, the engine that drafted this article, is a Claude-native self-improving routine; dreaming is the productized version of the retrospective we currently run by hand.",
      "> The moat was never \"can you build an agent loop.\" It is whether you can define the rubric, design the memory, and lay out the topology.",
      "The throughline is the one we have argued since the start: the moat was never \"can you build an agent loop.\" It is whether you can define the rubric, design the memory, and lay out the topology for a specific domain. That is consulting and architecture work — Strategy-to-Ship — and it is exactly where fifteen years of structured delivery beats raw build speed.",
      "## What to do about it",
      "- [ ] **Write the rubric before the agent.** If you cannot state \"good\" as acceptance criteria, no model will reliably hit it. Begin every agent project with the grading spec, not the prompt.",
      "- [ ] **Treat memory as architecture, not a feature.** Decide up front what should persist, what dreaming should curate, and who reviews changes before they land — especially in regulated environments.",
      "- [ ] **Decompose before you parallelize.** Map which work is a lead-agent decision and which belongs to a specialist subagent. Most stalled agents are one over-stuffed agent doing four jobs badly.",
      "- [ ] **Build on the harness, not a single model.** Models change weekly and can be withdrawn; the runtime, rubrics, and memory you build around them are what compound.",
      "We are adding Managed Agent deployments to our [Agentic Systems track](/services) — the self-improving, self-grading tier of what we build. If your pilots keep stalling just short of production, that gap is a rubric-and-architecture problem, and it is the work we do. [Get in Touch](/contact).",
      "**Powered by Enso Labs**",
    ],
  },
  {
    slug: 'frontier-ai-routing-us-financial-services',
    title: 'Codex 5.5 or Fable 5? How we choose the right frontier model, build by build.',
    dek: 'OpenAI\'s Codex now runs GPT-5.5; days later Anthropic shipped Claude Fable 5 — two flagship coding models, neither \'best\' at everything. From inside OpenAI\'s Builder Lounge at NY Tech Week, here is the working rule we use to route between Codex 5.5, Fable 5, Claude Opus 4.8, and Gemini on real builds — and why the right choice now changes almost every week. Forward-deployed, so a 20-person company or a global enterprise gets the frontier without standing up its own AI research bench.',
    pillar: 'Consult',
    date: '2026-06-09',
    dateModified: '2026-07-13',
    readingMinutes: 8,
    tags: ['Fable 5', 'Claude Opus 4.8', 'GPT-5.5', 'Codex', 'Gemini', 'Frontier Models', 'Forward-Deployed', 'Managed Agents', 'Model Routing', 'Agentic AI', 'AI Adoption', 'SMB AI', 'Enterprise AI', 'OpenAI Builder Lounge', 'NY Tech Week', 'Enso Labs', 'Sav Banerjee'],
    faqs: [
      {
        question: 'What is Claude Fable 5?',
        answer: 'Claude Fable 5 (API id claude-fable-5) is Anthropic\'s strongest generally available model, launched June 9, 2026. It leads the field on agentic coding (SWE-Bench Pro 80.3%) and knowledge work (GDPval-AA 1932). It ships with a safety-router design: classifiers route cybersecurity, biology, and model-distillation queries to Claude Opus 4.8, and the unguarded version (Mythos 5) is gated to vetted partners. It runs $10/$50 per million tokens, double Opus 4.8.',
      },
      {
        question: 'How often are new frontier AI models released in 2026?',
        answer: 'Often enough that \'which model is best\' changes almost weekly. In one six-week span in 2026, Anthropic shipped Claude Opus 4.8 (May 28) and Claude Fable 5 (June 9), OpenAI\'s GPT-5.5 began powering Codex, and Google shipped Gemini 3.5 Flash at I/O. Each leads on different work, so the right choice is a per-job decision that has to be re-tested as new models land.',
      },
      {
        question: 'What is a forward-deployed AI studio?',
        answer: 'A forward-deployed studio embeds with a client to build and operate AI systems in production rather than handing over a strategy deck. For frontier models specifically, it means continuously testing each new release against the client\'s real workloads, routing the best model to each job, and keeping the system current as the leaderboard moves — so the client gets frontier capability without staffing its own AI research team.',
      },
      {
        question: 'Should a company standardize on a single AI model?',
        answer: 'Usually no. As of 2026 no single model leads on every task — one is strongest on long-horizon coding, another is the honest default on sensitive data, another is the speed-and-cost option. Standardizing on one means overpaying on the work it was not built for and falling behind when a better model ships. A routing approach — matching the model to the task and re-testing as new models arrive — beats vendor loyalty.',
      },
    ],
    body: [
      '![A founder shows the room a workflow their dev team built on Codex 5.5 — at the Builder Lounge, the demos from the floor, not the keynote, are the point.](/images/insights/openai-builder-lounge-03.jpg)',
      '![OpenAI\'s Builder Lounge during NY Tech Week — a room of founders and engineers building live on the newest models. June 4, 2026. Photography: Alex Korolkovas](/images/insights/openai-builder-lounge-04.jpg)',
      'The hard part of enterprise AI is no longer which model is best. It is that the answer changes almost every week — and almost no team is staffed to keep up. The advantage now goes to whoever can test each new frontier model against real work the week it ships, and route the winner into production. For most companies, that is not a hire. It is a partner.',
      'We spent a working afternoon at OpenAI\'s Builder Lounge during NY Tech Week, at their SoHo office — building with Codex alongside the engineers who ship it, with unlimited model access and an open AMA. The point of the room was not the keynote; it was the keyboards. Founders and engineers stress-testing the newest model against real workloads, in real time. That is the habit the whole business now runs on: when a model ships, we are already playing with it.',
      '![Enso Labs in the room — testing the newest Codex against real work, the week it shipped.](/images/insights/openai-builder-lounge-01.jpg)',
      '## The frontier ships on a weekly cadence now',
      'Count the last six weeks. [Claude Opus 4.8](https://www.anthropic.com/news/claude-opus-4-8) landed May 28. [GPT-5.5](https://openai.com/index/introducing-gpt-5-5/) became the model powering Codex. Google shipped [Gemini 3.5 Flash](https://deepmind.google/models/gemini/) at I/O. And today, Anthropic released [Claude Fable 5](https://www.anthropic.com/news/claude-fable-5-mythos-5) — its strongest publicly available model, leading the field on agentic coding (SWE-Bench Pro 80.3%) and knowledge work (GDPval-AA 1932), with a safety-router design that quietly hands sensitive queries back to Opus 4.8. Four serious releases in six weeks. By the time a team finishes evaluating one, the next is out.',
      '| Model | SWE-Bench Pro | Knowledge work (GDPval-AA) | Price /M tokens | What it\'s best at |\n| --- | --- | --- | --- | --- |\n| **Claude Fable 5** | 80.3% | 1932 | $10 / $50 | The hardest, long-horizon coding and knowledge work; shipped today. |\n| **Claude Opus 4.8** | 69.2% | 1890 | $5 / $25 | The honest, cheaper default; most reliable about its own failures. |\n| **GPT-5.5 (Codex)** | 58.6% | 1769 | $5 / $30 | Sustained terminal sessions and GitHub-native work. |\n| **Gemini 3.1 Pro / 3.5 Flash** | 54.2% | 1314 | varies | Google-ecosystem fit and roughly 4x faster, cheaper throughput. |',
      'Source: [Anthropic\'s Fable 5 benchmark table](https://www.anthropic.com/news/claude-fable-5-mythos-5), June 9, 2026. Fable 5\'s published cybersecurity and biology figures belong to the gated Mythos 5; the deployable Fable 5 falls back to Opus 4.8 on those by design.',
      'Read the table and the trap is obvious: there is no single “best” model anymore. Fable 5 leads on hard, long-horizon coding; Opus 4.8 is the honest, cheaper default; GPT-5.5 in Codex owns sustained terminal work; Gemini 3.5 Flash is the speed-and-cost play. Standardize on one and you overpay on the work it was not built for — and you are wrong again the week the leaderboard moves.',
      '![Building with the newest Codex against workloads we already run in production](/images/insights/openai-builder-lounge-02.jpg)',
      '## Why this is an opportunity, not a problem',
      'For a 20-person company, evaluating four frontier models a month is impossible — there is no spare engineer to benchmark Fable 5 against last week\'s stack. For a large enterprise it is slower, not faster: a committee, a procurement cycle, and a model that is two generations old by the time it clears review. Either way the cost is the same — running last month\'s model on this month\'s problems, or betting the roadmap on a single vendor. The companies pulling ahead are not the ones with the biggest AI teams; they are the ones who have made frontier testing somebody\'s standing job.',
      'That is the whole opening for a forward-deployed studio. We do the part that does not scale inside one company: we live in these rooms, we play with each model the week it ships, and we already know — from real workloads, not press releases — which one to reach for. For regulated teams that testing has to be auditable too, which is its own reason to have an operator rather than a science project. But the need is universal: the frontier now moves faster than any single team can track.',
      '## The Enso take: we test the frontier so you can ship on it',
      'This is the work we do, and it is why we are in the room. We are a forward-deployed, build-and-operate studio — for a Fortune 500 manufacturer whose scientists trust only intelligence they can inspect, for Heller\'s pharma AI Center of Excellence shipping compliant work from day one, and in our own Enso Trading Terminal, where we run frontier models against live markets. Every one of those started the same way: playing with the newest models until we knew exactly which to trust with which job.',
      'We do not hand a client a model recommendation that is stale in a week. We stand up and operate a governed routing layer — managed agents — that picks the right model per task and swaps in a new one when it earns its place. The default we run by:',
      '| The job | We reach for | Why |\n| --- | --- | --- |\n| Long builds, migrations, sustained terminal work | **Fable 5** or **GPT-5.5 (Codex)** | Long-horizon execution that runs for an hour without losing the thread. |\n| Hard reasoning, ambiguous judgment, large codebases | **Fable 5** or **Opus 4.8** | Strongest judgment under ambiguity; Fable 5 when the build is genuinely hard. |\n| Anything on sensitive or production data | **Opus 4.8** | The most honest about its own failures; the conservative, cheaper default. |\n| High-volume, latency- or cost-sensitive work | **Gemini 3.5 Flash** or **Opus 4.8** | Roughly 4x faster, cheaper, where the judgment bar is lower. |\n| One-off scripts, glue, throwaway tooling | Either | Route on cost and whichever terminal is already open. |',
      'The routing rule is the deliverable; the testing habit behind it is the moat. When Fable 5 shipped this morning, our clients did not have to do anything — we were already benchmarking it against their workloads by lunch.',
      '## What to do about it',
      '**Stop standardizing on one model.** The best model is now a per-job, per-week decision. Build a routing habit — match the model to the task — instead of a vendor loyalty you will regret the next time the leaderboard moves.',
      '**Make frontier testing somebody\'s standing job.** Whether it is an internal pod or a forward-deployed partner, someone has to be playing with each release the week it ships. The cost of not doing it is invisible until you are two generations behind.',
      '**Measure cost per shipped result, not per token.** A pricier model that finishes in one pass can be cheaper than a cheap one that needs three. Track dollars-per-completed-task across models, not sticker price.',
      '**Buy the operator, not the model.** For most companies the answer is not a bigger AI team — it is a forward-deployed studio that tests, routes, and operates the frontier for you, and keeps the system current as the models change underneath it.',
      'A new frontier model shipped this morning. Another will ship next week, and the week after that. The companies that win the next phase are not the ones who pick the right model today — they are the ones who never have to pick alone. That is the room we live in, and the service we sell.',
      'This is the core of our [AI transformation services](/services): a governed, forward-deployed routing layer that picks the right model per task and swaps in a new one when it earns its place — operated for you. If your team is standardizing on one model, or has no one testing the frontier the week it ships, [get in touch](/contact).',
      'Powered by Enso Labs',
    ],
  },
  {
    slug: 'google-io-hackathon-managed-agents-omni-antigravity',
    title: 'Inside the Google I/O Hackathon: 150 Builders, Managed Agents, and the New Google Agent Stack.',
    dek: 'Forty-eight hours after Google DeepMind shipped Gemini Omni, Antigravity 2.0, and the new Managed Agents API at I/O 2026, Cerebral Valley convened 150-plus builders at SHACK15 in San Francisco. I was in the room as a Google partner — not a competitor — to talk to builders, observe the new stack under load, and feature the work that will matter twelve months from now. Part 1 of a two-part series on Google I/O 2026.',
    pillar: 'Build',
    date: '2026-05-26',
    dateModified: '2026-07-02',
    readingMinutes: 8,
    tags: ['Google I/O', 'Gemini Omni', 'Antigravity 2.0', 'Managed Agents', 'Google DeepMind', 'Cerebral Valley', 'AI Agents', 'Hackathon', 'Agentic Systems', 'Gemini 3.5 Flash', 'Fortune 500', 'AI Strategy', 'AI Transformation', 'Enso Labs', 'Sav Banerjee'],
    faqs: [
      {
        question: 'What happened at the Google I/O 2026 hackathon?',
        answer: 'The Cerebral Valley × Google I/O Hackathon took place on May 23, 2026 at SHACK15 in San Francisco, two days after Google DeepMind shipped Gemini Omni, Antigravity 2.0, the Managed Agents API, and Gemini 3.5 Flash at I/O 2026. Over 150 builders competed, with Yves Hughes winning 3rd place overall and the dedicated Managed Agents bonus track — the marquee category of the weekend.',
      },
      {
        question: "What is Google's Managed Agents API?",
        answer: "Google's Managed Agents API, announced at I/O 2026, lets developers spin up an agent that reasons, uses tools, and executes code inside an isolated Linux environment — powered by the Antigravity agent harness, built on Gemini 3.5 Flash, available through the Interactions API and Google AI Studio. It collapses six weeks of custom harness engineering into a single API call.",
      },
      {
        question: 'What is Antigravity 2.0?',
        answer: "Antigravity 2.0 is Google DeepMind's agentic coding and orchestration platform, redesigned at I/O 2026 to center on the agent rather than the code editor. A manager agent decomposes tasks into subtasks and dispatches specialized agents in parallel — one writing code, one running terminal commands, one testing in the browser — all coordinated through an SDK co-optimized for Gemini 3.5 Flash.",
      },
    ],
    body: [
      'My friend [Yves Hughes](https://www.linkedin.com/in/yvesjr/) just won 3rd place at the Google I/O Hackathon — and the bonus track for **Managed Agents**, the marquee Google announcement of I/O 2026. He beat more than 150 competing submissions over a single Saturday. I was in the room, watching the new Google agent stack get stress-tested by the people building production AI agents on it — the exact signal Enso Labs tracks for our Fortune 500 clients.',
      'Forty-eight hours earlier, on May 19, Google DeepMind [announced Gemini Omni, Antigravity 2.0, the new Managed Agents API, and Gemini 3.5 Flash](https://blog.google/innovation-and-ai/technology/developers-tools/google-io-2026-developer-highlights/) at the I/O 2026 keynote. By Saturday morning, Cerebral Valley had convened 150-plus builders at SHACK15 in San Francisco to be the first to ship on a stack that had not existed at the start of the work week. The fastest path from a Google product launch to a production implementation is now measured in hours, not quarters.',
      'I attended as a Google partner — not as a hackathon competitor. The job was to talk to builders, observe what they were trying to push the new APIs to do, and surface the work I expect to be referencing in Fortune 500 client conversations through the rest of 2026. Yves\' win is the first of those references. This article is the rest.',
      '![Google I/O Hackathon by Cerebral Valley — May 23, 2026, SHACK15 San Francisco](/images/insights/google-io-hackathon-06.jpg)',
      '## What Google Shipped on Monday That Made the Weekend Possible',
      'The I/O 2026 keynote was not a model launch. It was the unveiling of a coherent agent stack — four announcements that fit together as a single platform play.',
      '**Gemini Omni** is Google DeepMind\'s new world model — an any-to-any generative system that fuses Gemini reasoning with DeepMind\'s Veo, Nano Banana, and Genie components. The keynote demo was a glass marble rolling down a complex chain-reaction track, with the model anticipating physics, gravity, and kinetic motion at every frame. Omni does not just generate video. It predicts what should happen in a physical world and renders accordingly.',
      '**Antigravity 2.0** is the platform\'s biggest reset since it launched in November 2025. The product no longer centers on a code editor. It centers on the agent. A manager agent decomposes a task into subtasks, then dispatches specialized agents in parallel — one writing code, one running terminal commands, one testing in the browser — all coordinated through an SDK co-optimized for Gemini 3.5 Flash. DeepMind engineer Varun Mohan demoed it [building a functioning operating system from scratch in twelve hours](https://blog.google/innovation-and-ai/technology/developers-tools/google-io-2026-developer-highlights/). The platform also integrates **CodeMender**, DeepMind\'s autonomous security agent, which has already upstreamed 72 security fixes to open-source projects across codebases up to 4.5 million lines.',
      '**Gemini 3.5 Flash** is the engine making everything run. It outperforms Gemini 3.1 Pro across almost every benchmark while running four times faster than peer frontier models. The strategic point Google made on stage was unambiguous: Flash is not a budget tier. Flash is the new default for production agentic workflows.',
      '**Managed Agents** is the API that ties the stack together. With a single call, developers can now spin up an agent that reasons, uses tools, and executes code inside an isolated Linux environment — powered by the Antigravity agent harness, built on Gemini 3.5 Flash, available through the Interactions API and Google AI Studio. This was the launch the hackathon was specifically designed to stress-test.',
      '![Inside SHACK15 — Cerebral Valley × Google I/O Hackathon, the largest turnout in the series to date](/images/insights/google-io-hackathon-03.jpg)',
      '## Three Strategic Takeaways From the Weekend',
      'Beyond the leaderboard, three patterns surfaced across the room. These are the patterns I am taking into Fortune 500 client conversations this week.',
      '**Multi-agent orchestration is becoming the default.** Antigravity 2.0\'s manager-and-specialist pattern is not a feature. It is a re-architecture. Builders who started Saturday morning with single-agent loops finished the day with multi-agent compositions. Single-agent frameworks will look quaint within six months. Enterprise architects who are still scoping "pilot one AI assistant" should re-scope to "pilot a team of agents."',
      '**Managed Agents collapses the production-agent learning curve.** What used to take an enterprise platform team six weeks of harness work — sandboxing, tool routing, code execution isolation — Google now ships as a single API call. For Fortune 500 transformation programs, this changes the build-versus-buy math on every agent initiative. The question is no longer "can we build the harness?" It is "do we still need our own harness, or do we adopt Managed Agents and redirect that engineering capacity to domain logic?"',
      '**Omni\'s world model is a separate strategy entirely.** Most of the room was head-down on Managed Agents and Antigravity. Omni was largely treated as future-state. That is a tell. Omni\'s physics-aware video generation is going to reprice product visualization, robotics simulation, and high-volume training content over the next twelve months — but the enterprise adoption curve is slower than the agent stack. CMOs and Chief Innovation Officers who pre-stage their Omni evaluation now will move faster than the ones who wait for the case studies.',
      '![Bay Bridge view from SHACK15 — builders shipping on Gemini 3.5 Flash and the Managed Agents API, 48 hours after Google I/O 2026](/images/insights/google-io-hackathon-04.jpg)',
      '## Featured Builder: Yves Hughes Won the Marquee Track',
      '[Yves Hughes](https://www.linkedin.com/in/yvesjr/) — AI Executive Coach and self-described "Enterprise PM who is actively building AI" — took home 3rd place at the Google I/O Hackathon and won the dedicated bonus track for **Managed Agents**. The Managed Agents bonus was, by any honest measure, the marquee category of the weekend. Managed Agents was Google\'s headline launch on Monday. Three days later, Yves had shipped the implementation that beat more than 150 competing builds on the metric Google itself defined as the prize.',
      'What makes this notable is not just the medal. It is the positioning. Yves is not a twenty-two-year-old infrastructure engineer. He is a senior enterprise product leader and AI executive coach who put his name on a Managed Agents implementation that won inside Google\'s own house — against a room that included seasoned platform engineers and YC-backed founders. The signal — that experienced enterprise builders can outship pure infrastructure specialists on the new frontier stack — is the same signal Enso Labs is built on.',
      'Yves\' full post on the win, with hackathon photos: **[LinkedIn →](https://www.linkedin.com/posts/yvesjr_just-won-3rd-at-the-google-io-hackathon-activity-7464175320552607744-JLrX)**',
      '## What This Means for Fortune 500 AI Strategy',
      'The Google I/O 2026 announcement was not a model launch. It was a coherent agent stack. Omni handles world modeling and multimodal generation. Antigravity 2.0 handles multi-agent orchestration and autonomous coding. Managed Agents handles the production runtime. Gemini 3.5 Flash is the engine underneath all of it. For the first time, Google is competing on a stack that matches the depth of the Anthropic and OpenAI agent platforms — and on multi-agent orchestration with security baked in via CodeMender, Google is now ahead.',
      'For the Fortune 500 transformation leaders we work with, this is the moment to do three things in the next ninety days. First, run a Managed Agents pilot against one production workflow already running on a custom harness — measure the engineering capacity you free up. Second, evaluate Antigravity 2.0 in one engineering team and quantify the velocity delta versus your existing toolchain. Third, commission an Omni feasibility study against your largest existing video, training, or product visualization spend line. None of these is a 2027 decision. Each one is decidable by the end of Q3.',
      '![SHACK15 at the San Francisco Ferry Building — venue for the Cerebral Valley × Google I/O Hackathon](/images/insights/google-io-hackathon-01.jpg)',
      '## What Comes Next',
      'Cerebral Valley\'s next stop is Paris in July — the [RAISE Summit](https://raisesummit.com/) on July 4 and 5, followed by the Machina Hackathon on July 6. Google also announced the [Build with Gemini XPRIZE](https://www.xprize.org/news/xprize-launches-hackathon-with-2-million-prize-pool-backed-by-google) on the keynote stage: $2 million in prizes for 90 days of building real businesses on Gemini. The agent ecosystem is no longer a single venue. It is a global circuit running quarterly, and the builders who win it twice are about to define the next twelve months.',
      '[Part 2 of this series](/insights/google-io-after-hours-deepmind-strategy-signal) covers the I/O after-hours circuit — two nights with Google DeepMind in San Francisco where the strategic signal lived between the demos. If you are a Fortune 500 leader deciding what to do with Omni, Antigravity, and the new Managed Agents API, this is the question Enso Labs is built to answer with you. Explore our [AI transformation services](/services) or [get in touch](/contact).',
    ],
  },
  {
    slug: 'google-io-after-hours-deepmind-strategy-signal',
    title: 'Google I/O After-Hours: Two Nights With Google DeepMind and the Strategic Signal Behind the Demos.',
    dek: 'The Google I/O 2026 keynote announced Gemini Omni, Antigravity 2.0, the Managed Agents API, and Gemini 3.5 Flash. But the keynote is where the marketing lives. The after-hours is where the strategy gets decided. Two nights in San Francisco — Google for Startups × DeepMind on Tuesday, Cerebral Valley × DeepMind at Corgi Cafe on Friday. Part 2 of a two-part series.',
    pillar: 'Consult',
    date: '2026-05-26',
    dateModified: '2026-07-02',
    readingMinutes: 7,
    tags: ['Google I/O', 'Google DeepMind', 'Cerebral Valley', 'AI Strategy', 'Gemini Omni', 'Antigravity 2.0', 'Managed Agents', 'Pomelli', 'Stitch', 'Fortune 500', 'AI Transformation', 'Thought Leadership', 'AI Agents', 'Hackathon', 'Enso Labs', 'Sav Banerjee'],
    faqs: [
      {
        question: 'What strategic signals came from Google I/O 2026?',
        answer: 'Three strategic signals emerged from Google I/O 2026 after-hours events: (1) Google is betting the company on agentic AI, not chat — Omni plus Antigravity plus Managed Agents is a coherent agent-first strategy; (2) DeepMind is now Google\'s product team, not its research lab — DeepMind staffers ran the keynote demos and product booths; (3) Cerebral Valley is emerging as the new accelerator class, running a quarterly global hackathon circuit that is becoming the highest-signal builder event series in AI.',
      },
      {
        question: "What is Google DeepMind's product strategy after I/O 2026?",
        answer: "Google DeepMind's I/O 2026 strategy centers on a coherent agent stack: Gemini Omni for world modeling and multimodal generation, Antigravity 2.0 for multi-agent orchestration and autonomous coding, Managed Agents for the production runtime, and Gemini 3.5 Flash as the engine underneath all of it. Three product cycles to watch: Antigravity 2.5, Omni 2, and the Build with Gemini XPRIZE ($2M, 90-day competition closing Q3 2026).",
      },
      {
        question: 'How does Antigravity 2.0 change enterprise AI?',
        answer: "Antigravity 2.0 changes enterprise AI by shipping the harness layer that historically separated platform companies from product companies. Its manager-and-specialist multi-agent pattern replaces single-agent loops, and combined with Managed Agents, it collapses six weeks of custom platform engineering into a single API call. Enterprise architects should re-scope from 'pilot one AI assistant' to 'pilot a team of agents.'",
      },
    ],
    body: [
      'The Google I/O 2026 keynote announced Gemini Omni, Antigravity 2.0, the Managed Agents API, and Gemini 3.5 Flash — a coherent stack for building production AI agents. But the keynote is where the marketing lives. The after-hours is where the strategy gets decided, and the after-hours is the room Enso Labs reports from.',
      'Over the same week, I attended two of those rooms — the official **Google for Startups × Google DeepMind** reception on Tuesday May 19, and the **Cerebral Valley × DeepMind** closeout at Corgi Cafe on Friday May 22. Two nights, two crowds, two different signals from the same launch. Part 2 of a two-part series on Google I/O 2026 — [Part 1 covers the Cerebral Valley × Google I/O Hackathon featuring 3rd-place winner Yves Hughes →](/insights/google-io-hackathon-managed-agents-omni-antigravity).',
      '![Google I/O After Hours — Googler check-in and Guest check-in, the official Google for Startups × DeepMind reception, San Francisco](/images/insights/google-io-afterhours-05.jpg)',
      '## Night One: Google for Startups × Google DeepMind, Tuesday May 19',
      'The official Tuesday reception was the largest of the I/O week. The crowd was a curated mix of founders, investors, and Googlers, brought together by Google for Startups in partnership with the Google DeepMind team. The agenda was deceptively simple: ambient music, conversation, and walk-up demos of the products that had landed in the keynote earlier that day.',
      'The product booths told the actual story Google wanted to be told. **[Pomelli](https://blog.google/innovation-and-ai/models-and-research/google-labs/pomelli-agentic-capabilities/)** — Google Labs\' AI brand-builder, newly upgraded with Gemini 3.5 Flash and deeper Antigravity 2.0 integration — was running brand books and full websites end-to-end in front of the audience. **Stitch** — Google\'s real-time AI design tool now built on a streaming generation model with multiplayer canvas editing — was being demoed continuously by the team that built it. **Gemini Live** and **Gemini Robotics ER 1.5** had a third station for the embodied-AI conversations.',
      '![Google Labs activations at the I/O 2026 After Hours — Pomelli, Stitch, and the Gemini Live / Robotics ER 1.5 demo wall](/images/insights/google-io-afterhours-01.jpg)',
      'What got the most floor time in conversation was not Pomelli, not Stitch, and not the robotics work. It was **Antigravity 2.0** and **Managed Agents**. The product launches that read as "developer tooling" on the slides read very differently in a room full of founders looking at their cap tables. The implication: Google has now shipped the harness layer that historically separated platform companies from product companies. Every founder I talked to was working through the same recalculation — if Managed Agents costs less than custom infrastructure and replaces six weeks of platform engineering, where does our differentiation move next?',
      '![Daytime atrium reception — Google for Startups × Google DeepMind After Hours, San Francisco](/images/insights/google-io-afterhours-02.jpg)',
      '## Night Two: Cerebral Valley × Google DeepMind at Corgi Cafe, Friday May 22',
      'By Friday evening the I/O launch energy had compressed. The Corgi Cafe gathering was [hosted by Cerebral Valley with the Google DeepMind team](https://luma.com/deepmind) — smaller, more technical, more research-adjacent. Where the Tuesday reception was about the product launches, the Friday closeout was about what comes next.',
      'The conversations were noticeably more candid. DeepMind researchers were not in keynote mode. They were in debrief mode. The launches that had read as polished on Monday were now being discussed with the actual rough edges named — where Omni\'s physics simulation still degrades, where Antigravity 2.0\'s manager-agent loop still over-orchestrates simple tasks, where the Managed Agents harness performs differently than the live demos suggested.',
      '![Entry to the Cerebral Valley × Google DeepMind closeout — Corgi Cafe, San Francisco, Friday May 22](/images/insights/google-io-afterhours-03.jpg)',
      'The candor matters. If you only read the press coverage, you get the surface narrative. If you are in the room when the people who built the system describe what they wish they had shipped differently, you get the real product roadmap six months earlier than the next public announcement. Friday was that room.',
      '![Lounge conversations at the Cerebral Valley × Google DeepMind Post-I/O closeout — Corgi Cafe](/images/insights/google-io-afterhours-04.jpg)',
      '## Three Strategic Signals From the Two Rooms',
      'Three signals were consistent across both nights. These are the patterns I am taking into Fortune 500 client conversations this quarter.',
      '**Google is betting the company on agentic, not chat.** Omni plus Antigravity plus Managed Agents is a coherent agent-first strategy, not a model release. This is structurally different from OpenAI\'s chat-and-API motion. For enterprise transformation leaders, this matters — Google now has the platform depth to be a credible primary vendor for an agent-first transformation program, not just a model vendor inside a multi-vendor stack.',
      '**DeepMind is now Google\'s product team, not Google\'s research lab.** Three years ago DeepMind shipped papers. Today DeepMind shipped the keynote. Varun Mohan demoed Antigravity building an operating system live on stage. Multiple DeepMind staffers ran the product booths Tuesday night and the debrief Friday night. The org chart shift is the strategy shift. Anyone evaluating Google Cloud\'s enterprise AI roadmap should re-weight DeepMind heavily in the credibility math.',
      '**Cerebral Valley is the new accelerator class.** Not Y Combinator. Not a16z. Not Sequoia Scout. A community of model labs plus curated builders plus curated capital — running a quarterly hackathon circuit that is rapidly becoming the highest-signal builder events of the year. The Paris July events ([RAISE Summit](https://raisesummit.com/) July 4-5, Machina Hackathon July 6) confirm this is a global motion. For founders and corporate development teams trying to get inside the next launch cycle of a frontier model, the Cerebral Valley calendar is now table stakes.',
      '## What Comes Next',
      'Three product cycles to watch over the next two quarters. **Antigravity 2.5** — the multi-agent orchestration is shipping fast enough that another release inside calendar 2026 is realistic; the next version will likely formalize agent-to-agent communication primitives that did not make 2.0. **Omni 2** — DeepMind\'s roadmap on world models is more ambitious than what shipped on Monday; the interactive use cases (robotics simulation, real-time physics) are a bigger story than video generation. **The [Build with Gemini XPRIZE](https://www.xprize.org/news/xprize-launches-hackathon-with-2-million-prize-pool-backed-by-google)** — Google\'s $2 million, 90-day hackathon competition announced on the I/O stage closes in Q3, and the winning projects will define what a "production agentic business" looks like at Google scale.',
      '## For C-Suite Leaders Reading This',
      'If you have not already initiated a Google Cloud relationship conversation around the I/O 2026 stack, the next thirty days are the moment. Google\'s GTM team is in full follow-up motion right now — I received outreach from Google Cloud titled "From Next \'26 to Production: Let\'s connect" within forty-eight hours of returning from San Francisco. The combination of Managed Agents (commodity), Antigravity 2.0 (differentiation), and Omni (long bet) is the exact mix that warrants a structured Q3 evaluation against your existing Anthropic and OpenAI footprints.',
      'Part 1 of this series covers the Cerebral Valley × Google I/O Hackathon and features 3rd-place winner Yves Hughes. [Read Part 1 →](/insights/google-io-hackathon-managed-agents-omni-antigravity). If you are mapping a Q3 AI transformation roadmap and want a partner-tier read on Google\'s new stack — and where Anthropic and OpenAI fit alongside it — explore our [AI transformation services](/services) or [get in touch](/contact).',
    ],
  },
  {
    slug: 'notion-career-agent-open-source-hackathon',
    title: 'Notion Just Launched a Developer Platform. We Shipped an Open-Source Career Agent on Day One.',
    dek: 'Three days after Notion unveiled Workers, MCP, and an Agent SDK, we were at their first hackathon in San Francisco — building a career intelligence agent that anyone can fork and deploy today.',
    pillar: 'Build',
    date: '2026-05-19',
    dateModified: '2026-06-02',
    readingMinutes: 8,
    tags: ['AI Agents', 'Notion', 'Notion Workers', 'MCP', 'Claude', 'Open Source', 'Hackathon', 'TypeScript', 'Career Intelligence', 'Agentic Systems', 'Anthropic', 'Developer Platform'],
    body: [
      'On May 13, Notion [launched a developer platform](https://www.notion.com/releases/2026-05-13) that turns every workspace into an AI agent hub — Workers for custom code, MCP for data access, an Agent SDK for external integrations, and a CLI for deployment. [TechCrunch called it](https://techcrunch.com/2026/05/13/notion-just-turned-its-workspace-into-a-hub-for-ai-agents/) a move that positions Notion as an orchestration layer where people and agents collaborate across tools and databases. Three days later, we were at Notion HQ in San Francisco for their first-ever Developer Platform Hackathon.',
      'We shipped a career intelligence agent in 24 hours — five Notion Worker tools, 487 lines of TypeScript, a full pipeline from job scanning to AI-tailored resume generation. **The project is open source and ready to fork.** [github.com/nycsav/notion-career-agent](https://github.com/nycsav/notion-career-agent)',
      '![Welcome hackers — Notion Developer Platform Hackathon, sponsored by Anthropic, Vercel, and OpenAI](/images/insights/notion-hackathon-01.jpg)',
      '## Notion\'s Developer Platform: What Launched and Why It Matters',
      'The [Notion Developer Platform](https://www.notion.com/product/developer-platform) is the biggest expansion of Notion\'s capabilities since the API launched in 2021. Over 1 million custom agents have already been built since Notion introduced AI agents in February 2026. The developer platform gives builders the primitives to go much further:',
      '**Notion Workers** are sandboxed TypeScript functions that run on Notion\'s infrastructure. No servers, no deployment pipelines — you write the logic and deploy with the Notion CLI. Workers are free during beta, with credit-based pricing starting August 11, 2026.',
      '**Notion MCP** (Model Context Protocol) servers let any AI assistant — Claude, Codex, or your own agents — read and write Notion data natively. This is the data layer that makes Notion a genuine platform, not just a workspace.',
      '**The Agent SDK and External Agents API** bring external agents into Notion as native workspace participants. At launch, partners include Claude Code, Cursor, Codex, and Decagon.',
      '**Database Sync** pulls data from any API (Salesforce, Zendesk, Postgres) directly into Notion databases — making the workspace the single pane of glass for agent workflows.',
      'For builders, the implication is clear: you can now ship AI agents that live where your users already work, backed by Anthropic, Vercel, and OpenAI as platform sponsors.',
      '![Notion Hackathon — May 16-17, San Francisco, backed by Anthropic, Vercel, and OpenAI](/images/insights/notion-hackathon-02.jpg)',
      '## What We Built: An Open-Source Career Intelligence Agent',
      'Job seekers submit an average of 16 applications per week but spend less than 30 minutes customizing each one. Tailored resumes are 61% more likely to land interviews, but deep customization does not scale with manual effort. The existing tools are either spam cannons (mass-apply bots that tank your response rate) or glorified spreadsheets. We built a system that does the intelligence work — scanning, scoring, tailoring — while keeping the human in the loop for every decision that matters.',
      '## Five Notion Worker Tools, One Pipeline',
      'The career agent runs entirely inside a Notion workspace using Notion Workers — the same runtime powering Notion AI agents across the platform. No servers to manage, no infra to maintain. We built five Agent Tools that chain together into an end-to-end career pipeline:',
      '**scanJobs** parses job listings from LinkedIn email notifications, extracts structured data (title, company, location, salary, requirements), and scores each role against the user\'s career profile using Claude Haiku. Every job gets a match score from 0 to 100 with a written rationale. Jobs scoring 75+ get flagged for action.',
      '**tailorResume** is the heavy lifter. Give it a job listing and a base resume, and it generates an ATS-optimized resume and cover letter using Claude Sonnet — the stronger model, because resume quality directly affects interview conversion. It extracts ATS keywords from the listing, maps them against existing experience, and returns structured data ready to save as linked Notion pages.',
      '**getCareerInsight** turns the agent into a strategic career advisor. Salary negotiation data, interview prep, company research — direct and actionable, powered by Haiku for speed on quick Q&A.',
      '**configureAgent** lets the user set automation preferences: copilot (suggestions only), autopilot (acts with confirmation), or autonomous (full auto). You configure scan cadence, match threshold, target roles, locations, salary minimum, and notification channels. The agent adapts its behavior to your risk tolerance.',
      '**getAgentStatus** provides pipeline analytics — jobs scanned, scored, applied, interviewing, offered, rejected — filtered by time range. The control panel for knowing whether your job search machine is working.',
      '![The hackathon space at Notion HQ, Annie Street, San Francisco](/images/insights/notion-hackathon-03.jpg)',
      '## Two-Model Architecture: Matching Claude to Task Criticality',
      'We deliberately split the AI work across two Claude models — a pattern we call task-criticality routing. Haiku (claude-haiku-4-5) handles the high-volume, speed-sensitive operations: job scoring, career Q&A, classification. Sonnet handles the high-stakes generation: resume tailoring and cover letters where quality directly drives outcomes.',
      'This is not about cost optimization. It is about matching model capability to task criticality. A wrong match score wastes a click. A weak resume wastes an interview opportunity. The same two-model pattern applies to any Notion AI agent where you need both throughput and quality — customer support triage versus response drafting, lead scoring versus proposal generation.',
      '## Source-Tier Ranking: Not All Applications Are Equal',
      'We ported the source-tier ranking system from [Strategy to Ship](https://ensolabs.ai/insights), our market intelligence engine, into the career agent. Every job is classified by acquisition channel: Tier 1 (direct referral, ~50% interview rate) through Tier 5 (cold apply, ~2%). This changes the agent\'s behavior — a Tier 1 referral with a 60 match score still gets priority over a Tier 5 cold apply at 85.',
      'The system encodes what experienced job seekers already know intuitively: **who referred you matters more than how perfectly your resume matches.** Source-tier ranking is a general pattern — it applies equally to sales pipelines, content distribution, and investor outreach.',
      '![Building and presenting at the Notion Developer Platform Hackathon](/images/insights/notion-hackathon-05.jpg)',
      '## Building on Notion Workers: What We Learned',
      'Three observations from shipping Notion AI agents in production during the hackathon:',
      '**Speed to deployment is real.** We went from zero to five deployed Notion Worker tools in under 24 hours using Claude Code as the primary dev environment. The Notion CLI (`npx notion workers deploy`) handles packaging and deployment. The Notion SDK provides typed access to databases, pages, and blocks. The developer experience is the best we have seen for agent deployment.',
      '**Notion MCP changes the integration model.** With [Notion MCP](https://www.notion.com/product/developer-platform), any MCP-compatible AI assistant — Claude, Codex, your own agents — can read and write Notion data natively. The career agent stores every job, resume, and status update as structured Notion pages. That data is immediately accessible to any other Notion AI agent or MCP client without additional integration work.',
      '**The design patterns transfer.** We have been running Strategy to Ship on Firebase and Vercel for months. Porting its intelligence patterns (source-tier ranking, multi-model routing, structured output parsing) to Notion Workers took hours, not weeks. If you have built agentic systems on any modern runtime, you can build Notion AI agents.',
      '## Fork It, Ship It, Make It Yours',
      'The career agent is open source and ready to deploy. Fork the repo, plug in your own resume and career preferences, and you have a working career intelligence system inside your Notion workspace. The architecture patterns — multi-model routing, source-tier ranking, configurable automation levels — are designed to be portable to any domain.',
      '[Fork on GitHub →](https://github.com/nycsav/notion-career-agent)',
      '## What This Means for the Notion Ecosystem',
      'Notion\'s Developer Platform is the most significant expansion of a productivity tool into an AI agent runtime we have seen. With 1 million custom agents already built, Workers free through August, and partners like Anthropic and OpenAI backing the ecosystem, this is a genuine platform play — not a feature announcement.',
      'The workspace is the interface. The Worker is the runtime. Notion MCP is the data layer. For builders and enterprises evaluating where to ship their next AI agent, Notion just became a serious platform option.',
      'At Enso Labs, we build AI agents on Notion and every major platform. The career agent is a compressed case study of how we approach every engagement: decompose the workflow, insert AI where it creates the most leverage, keep humans in the loop where judgment matters. If you are evaluating Notion Workers for your team, [get in touch](/contact).',
    ],
  },
  {
    slug: 'why-deck-only-ai-consulting-fails-production',
    title: 'Why deck-only AI consulting dies on contact with production.',
    dek: 'The gap between a beautiful slide and a running system is where most enterprise AI initiatives quietly die. Here\'s the autopsy from fifteen years inside the room.',
    pillar: 'Consult',
    date: '2026-04-22',
    dateModified: '2026-05-26',
    readingMinutes: 7,
    tags: ['AI Consulting', 'Strategy-to-Ship', 'Enterprise AI', 'Production AI', 'AI Transformation'],
    body: [
      'Most AI consultancies have a wildly successful first ninety days. The deck lands. The roadmap is celebrated. The exec sponsor commits. Then the engagement ends — and the system never ships.',
      'The reason is structural, not motivational. A deck-only consultancy hands off the architecture to an internal team that never participated in the design, then walks away from the production realities — eval harnesses, governance, latency budgets, hallucination guardrails — that determine whether the thing actually runs.',
      'The fix is not better decks. The fix is **the same operator who designs the system also ships it.** That collapses the translation layer. Architecture decisions get made by the person who has to debug them at 2am.',
      'This is why the Strategy-to-Ship Framework is sequenced the way it is: Diagnose, Design, Build, Scale — with the same builder across every phase. The roadmap and the runtime are the same artifact.',
    ],
  },
  {
    slug: 'expert-lens-knowledge-encoding',
    title: 'The Expert Lens: encoding expert knowledge as toggleable rules.',
    dek: 'A scientist will never trust a black-box relevance score. Here\'s how we built a 9-rule expert lens that scientists could reason about — and turn off — one rule at a time.',
    pillar: 'Build',
    date: '2026-04-15',
    dateModified: '2026-05-26',
    readingMinutes: 9,
    tags: ['AI Agents', 'Expert Systems', 'MCP', 'Market Intelligence', 'Enterprise AI', 'Fortune 500'],
    body: [
      'The AI Market Intelligence Platform had one non-negotiable acceptance criterion: the lead scientist had to trust the relevance ranking. That meant no opaque embeddings-as-relevance, no LLM-as-judge with hidden criteria, no statistical magic.',
      'What worked: encoding the scientist\'s actual decision criteria as nine explicit, MCP-compatible rules. Temperature floor. Material class. Chemistry scope. PFAS sensitivity. Market size. Liability exposure. Recency. Novelty. The 200°C gap.',
      'Each rule is independently toggleable. The dashboard shows the score with the rule on and off. The scientist can A/B their own expertise against the system. That\'s where trust comes from — not from the score, but from the ability to interrogate it.',
      'The pattern generalizes: **wherever you need expert trust, encode the expert\'s heuristics explicitly, and make every one of them inspectable.**',
    ],
  },
  {
    slug: 'mcp-servers-new-saas-integration',
    title: 'MCP servers are the new SaaS integration layer.',
    dek: 'Every legacy SaaS connector — Salesforce, Slack, Notion, Looker — gets a second life as an MCP server. The companies that ship MCP first will own the agent-native enterprise.',
    pillar: 'Build',
    date: '2026-04-08',
    dateModified: '2026-05-26',
    readingMinutes: 6,
    tags: ['MCP', 'Model Context Protocol', 'SaaS', 'AI Agents', 'Enterprise Integration', 'Claude', 'Agentic Systems'],
    body: [
      'For two decades, enterprise software lived inside a tab. The unit of work was the screen. Integration meant Zapier, REST, or a poorly-maintained iPaaS connector.',
      'The Model Context Protocol changes the unit. The unit is now the tool call. An MCP server publishes a typed surface that any agent — Claude, Perplexity Computer, Gemini — can invoke autonomously, with structured input and structured output.',
      'The implication for B2B SaaS: every connector you have today should be reframed as an MCP server. The buyer will ask for it within twelve months. The companies that ship first own the agent-native distribution layer for the next decade.',
      'We build these. They are usually two- to six-week engagements, depending on auth complexity and surface area.',
    ],
  },
  {
    slug: 'rag-eval-harness-not-vector-store',
    title: 'Your RAG problem is an eval problem, not a vector-store problem.',
    dek: 'Teams burn months optimizing chunk sizes, hybrid retrieval, and reranker stacks. Then they ship — and discover they never had a reliable way to know if the answer was right.',
    pillar: 'Build',
    date: '2026-04-01',
    dateModified: '2026-05-26',
    readingMinutes: 8,
    tags: ['RAG', 'Eval Harness', 'LLM', 'Production AI', 'Vector Search', 'AI Architecture'],
    body: [
      'Most RAG systems we are asked to rescue have a sophisticated retrieval pipeline and a non-existent eval harness. The team can describe their reranker but cannot tell you the F1 on a held-out set of expert-graded answers.',
      'This is backwards. The eval harness is the spec. Without it, every change is a vibes-based experiment — chunk size up, chunk size down, embedding model swap, hybrid weight knob — with no way to know if you are getting better or worse.',
      'Build the eval first. Hand-grade fifty representative queries with expert ground truth. Score every change against that set. The retrieval architecture you end up with will be different — and shippable.',
    ],
  },
  {
    slug: 'autonomous-trading-risk-as-architecture',
    title: 'In autonomous trading, the kill-switch is the architecture.',
    dek: 'The Trading Terminal runs unattended. That is only possible because the risk caps, position sizing, and shut-off logic were designed before the alpha logic — not after.',
    pillar: 'Ship',
    date: '2026-03-25',
    dateModified: '2026-05-22',
    readingMinutes: 10,
    tags: ['Financial AI', 'Trading', 'Autonomous Systems', 'Risk Architecture', 'Enso Trading Terminal', 'AI Agents'],
    body: [
      'Most trading systems begin with the strategy: a signal, an indicator, an alpha. The risk layer arrives later, bolted on, and is the first thing to fail under stress.',
      'The Enso Trading Terminal was built backwards on purpose. The kill-switch came first. Risk caps were schemas, not config. Position sizing was a typed function with property tests, not a magic number in a YAML file.',
      'The result is a system that can run unattended without anyone losing sleep. Strategy code can be wrong. Risk code cannot.',
      'For client engagements building autonomous trading, the rule is the same: the risk surface is the architecture. Strategy is a plug-in.',
    ],
  },
  {
    slug: 'ai-coe-pharma-mlr-compliance',
    title: 'An AI Center of Excellence that ships MLR-compliant work.',
    dek: 'Pharma agencies cannot move fast and break things. Medical, Legal, and Regulatory review is non-negotiable. Here\'s how we built a CoE that compresses launches from three months to two weeks anyway.',
    pillar: 'Consult',
    date: '2026-03-18',
    dateModified: '2026-05-22',
    readingMinutes: 7,
    tags: ['Pharma AI', 'AI Center of Excellence', 'Compliance', 'MLR', 'Healthcare AI', 'Enterprise AI', 'AI Transformation'],
    body: [
      'The standard objection to AI in pharma marketing is compliance. MLR/PRC review, FDA fair balance, brand voice tolerance — every shortcut breaks one of them.',
      'The Heller Center of Excellence was designed around the constraint, not despite it. RAG retrieval is grounded in five brand knowledge bases that already encode MLR-approved language. Pre-flight scans run on every draft. The compliance burden is automated, not bypassed.',
      'The metric that matters: campaign launches dropped from three months to two weeks. Compliance review time barely moved — what compressed was everything before it.',
      'The lesson: regulated industries are not where AI fails. They are where it has the largest leverage, **if you treat compliance as the spec rather than the obstacle.**',
    ],
  },
  {
    slug: 'options-flow-decision-support-not-black-box',
    title: 'Options flow analytics: decision support, not black box.',
    dek: 'Unusual flow is a hypothesis, not a trade. The Options Lab is built to surface hypotheses, force the human to vet them, and only then route to execution.',
    pillar: 'Ship',
    date: '2026-03-11',
    dateModified: '2026-05-22',
    readingMinutes: 5,
    tags: ['Financial AI', 'Options Trading', 'Decision Support', 'Human-in-the-Loop', 'Trading Terminal'],
    body: [
      'The marketing of "AI-powered options flow" usually implies an oracle — feed it tickers, get trades. That is exactly the model that loses money.',
      'The Options Lab is a decision-support tool. It surfaces unusual flow, sweeps, and blocks; cross-references against the news intelligence feed and the implied volatility surface; and presents the operator with a vetting checklist before any execution route is enabled.',
      'The human is in the loop on purpose. The system is good at finding hypotheses. It is the operator\'s job to kill the bad ones — and the operator should have to actively click "send" on every one that survives.',
    ],
  },
  {
    slug: 'principal-led-vs-50-person-consultancy',
    title: 'A principal-led studio outperforms a 50-person consultancy on shipped systems.',
    dek: 'Counterintuitive — and structural, not heroic. Six things change when the advisor and the build team work as one unit.',
    pillar: 'Consult',
    date: '2026-03-04',
    dateModified: '2026-05-22',
    readingMinutes: 6,
    tags: ['AI Consulting', 'Boutique Studio', 'Strategy-to-Ship', 'Principal-Led', 'Enterprise AI'],
    body: [
      'The pitch from a 50-person consultancy is depth of bench. The reality is hand-offs. Strategy decided in week 3 reaches engineering in week 9, refracted through three layers of partial context.',
      'A principal-led studio has structural advantages a large bench cannot replicate. Direct senior access — no account managers. Builder credibility — the advisor is also in the codebase. Dogfooding — the studio runs its own infrastructure. Speed — no approval chain. Selectivity — a fixed pipeline forces a yes to mean yes.',
      'The constraint is also real: bandwidth. A principal-led studio runs a small handful of deep engagements at a time. That is the whole point — depth, not portfolio. When the studio is at capacity, prospects hear so directly and get a future date.',
    ],
  },
  {
    slug: 'anthropic-financial-services-what-it-means',
    title: 'Anthropic Just Launched 10 Financial AI Agents. We Built Ours Last Year.',
    dek: 'Today Anthropic announced pre-built AI agents for banking and trading — pitchbook builders, credit memo drafters, statement auditors. Enso Labs has been shipping production financial agents since 2025. Here is what this means for the industry and why early movers have a structural advantage.',
    pillar: 'Ship',
    date: '2026-05-05',
    dateModified: '2026-07-13',
    readingMinutes: 6,
    tags: ['Financial AI', 'Anthropic', 'Claude', 'AI Agents', 'Trading', 'MCP', 'Enso Trading Terminal'],
    faqs: [
      {
        question: 'What did Anthropic announce for financial services in May 2026?',
        answer: "On May 5, 2026, Anthropic announced ten pre-built Claude AI agents for financial services — including pitchbook builders, credit memo drafters, portfolio summarizers, and statement auditors — with MCP-connected brokerage and market-data integrations built into the model layer. Enso Labs has been running production financial AI agents, including the Enso Trading Terminal, since 2025.",
      },
      {
        question: 'What structural advantage do early movers have in financial AI agents?',
        answer: "Firms that shipped financial AI agents in 2025 have roughly a year of production data, eval harnesses, and operational muscle a 2026 cold start cannot replicate. Anthropic's pre-built agents commoditize the basics — memo drafting, reconciliation, summarization; the moat is what you build on top: custom signal intelligence, firm-specific risk models, and compliance layers tuned to your regulatory surface.",
      },
      {
        question: 'Does Enso Labs build production financial AI agents?',
        answer: "Yes. Enso Labs builds and operates production financial AI agents on Claude and MCP, including the Enso Trading Terminal — news-driven trading algorithms, multi-agent research, options flow analysis, and brokerage API integration running autonomously since 2025. Scope an engagement at https://ensolabs.ai/contact.",
      },
    ],
    body: [
      'On May 5, 2026, Anthropic announced ten pre-built AI agents for financial services — pitchbook builders, credit memo drafters, portfolio summarizers, statement auditors. The announcement validates what we have been building at Enso Labs since 2025: production financial AI agents are not a research project. They are an operational layer.',
      'The Enso Trading Terminal has been running autonomously in production for over a year — news-driven trading algorithms, multi-agent research automation, options flow analysis, brokerage API integration via MCP. When Anthropic says Claude can now draft credit memos and audit financial statements, we hear confirmation of a thesis we have already shipped against: **the same reasoning engine that writes prose can manage risk, parse filings, and route orders.**',
      'What makes the Anthropic launch significant is not the agents themselves — it is the infrastructure underneath. Claude\'s financial services stack now includes MCP-connected brokerage APIs, compliance-aware reasoning, and audit-trail generation built into the model layer. This collapses the integration burden. A year ago, building a compliant trading agent meant wiring together four vendors. Now it means configuring one.',
      'The implication for enterprises: the window to build proprietary financial AI agents — and own the operational advantage — is compressing. The pre-built agents will commoditize the basics (memo drafting, statement reconciliation, portfolio summarization). The moat is in what you build on top: custom signal intelligence, firm-specific risk models, compliance layers tuned to your regulatory surface.',
      'Early movers have a structural advantage. The firms that shipped financial agents in 2025 — including our own terminal — have twelve months of production data, eval harnesses, and operational muscle that a cold start in 2026 cannot replicate. The question is no longer whether to build financial AI agents. It is whether you want to be the firm that built early or the firm that bought late.',
      'We build these systems. If you are a bank, asset manager, or fintech evaluating Claude\'s financial services stack, we can show you what a production deployment looks like — because we have been running one.',
    ],
  },
  {
    slug: 'mcp-brokerage-trading-model-context-protocol',
    title: 'MCP for Brokerage: How Model Context Protocol Is Connecting AI to Trading.',
    dek: 'Every brokerage API — Alpaca, Interactive Brokers, Schwab, TradeStation — is becoming an MCP server. This is the integration pattern that makes autonomous financial AI agents practical.',
    pillar: 'Build',
    date: '2026-05-08',
    dateModified: '2026-07-13',
    readingMinutes: 8,
    tags: ['MCP', 'Model Context Protocol', 'Brokerage', 'Financial AI', 'Trading', 'AI Agents', 'Alpaca', 'Interactive Brokers'],
    faqs: [
      {
        question: 'What is MCP for brokerage trading?',
        answer: "MCP (Model Context Protocol) for brokerage is a standardized way to wrap a brokerage API — Alpaca, Interactive Brokers, Schwab, TradeStation — into a typed tool surface that any AI agent can invoke natively. The agent calls a function like submit_order with a typed payload and receives a typed response, so the integration complexity lives in the MCP server, not the agent.",
      },
      {
        question: 'Why does MCP matter for autonomous trading agents?',
        answer: "MCP collapses bespoke, fragile per-vendor integrations into one typed interface, and lets pre-trade risk controls — position, notional, and order-rate limits — plus full audit logging live at the server layer. That makes autonomous financial AI agents practical and reviewable: every tool call is logged with inputs, outputs, timestamps, and the reasoning context that triggered it.",
      },
      {
        question: 'Does Enso Labs build MCP servers for brokerages?',
        answer: "Yes. Enso Labs builds and maintains production MCP servers connecting AI agents to Alpaca, Public.com, and crypto exchanges in the Enso Trading Terminal. These are typically two- to six-week engagements depending on auth complexity and surface area. Get in touch at https://ensolabs.ai/contact.",
      },
    ],
    body: [
      'The Model Context Protocol is the most consequential piece of AI infrastructure that almost no one in financial services is talking about. MCP is a standardized way for AI agents — Claude, Gemini, GPT — to invoke external tools with typed inputs and structured outputs. For trading, that means a single agent can check positions, submit orders, retrieve account data, and monitor fills as part of its reasoning loop.',
      'Before MCP, connecting an AI agent to a brokerage meant building a bespoke integration for every API. Alpaca REST endpoints, Interactive Brokers TWS, Schwab\'s OAuth2 flow, TradeStation\'s streaming WebSocket — each required custom auth, custom error handling, and custom response parsing. The result was fragile plumbing that broke every time a vendor updated their API.',
      'MCP collapses this. An MCP server wraps a brokerage API into a typed tool surface — function name, input schema, output schema — that any MCP-compatible agent can invoke natively. The agent does not need to know whether it is talking to Alpaca or Interactive Brokers. It calls `submit_order` with a typed payload and gets a typed response. The integration complexity lives in the server, not the agent.',
      'The architecture looks like this: the AI agent runs a reasoning loop — read breaking news, analyze the options chain, check the restricted list, calculate position sizing. When it decides to act, it calls an MCP tool. The MCP server validates the request against pre-trade risk controls (position limits, notional limits, order rate limits), then forwards it to the brokerage API. Every tool call is logged with inputs, outputs, timestamps, and the full reasoning context. That is the audit trail.',
      'We have been running this pattern in production since 2025. The Enso Trading Terminal connects to Alpaca, Public.com, and crypto exchanges via MCP servers that we built and maintain. The agent reads a news article about an FDA approval, checks the options chain for the relevant ticker, verifies risk limits, calculates sizing, and submits — all in one agentic loop. The entire flow is logged and reviewable.',
      'The practical implication for financial institutions: **MCP is the new SaaS integration layer for finance.** Every brokerage, market data provider, and compliance system should be evaluating how to publish an MCP surface. The firms that ship MCP servers first will own the distribution layer for the next generation of AI-native trading infrastructure. We build these servers. They are usually two- to six-week engagements.',
    ],
  },
  {
    slug: 'claude-partner-network-boutique-implementation',
    title: 'Why Boutique Firms Are the Right Claude Implementation Partner.',
    dek: 'Anthropic launched a $100M Claude Partner Network. Accenture, Deloitte, and PwC are in. But for production agentic systems, the structural advantages belong to boutique operators who build what they advise.',
    pillar: 'Consult',
    date: '2026-05-07',
    dateModified: '2026-07-13',
    readingMinutes: 7,
    tags: ['Claude', 'Anthropic', 'AI Consulting', 'Partner Network', 'Boutique Studio', 'Enterprise AI', 'Agentic Systems'],
    faqs: [
      {
        question: 'What is the Claude Partner Network?',
        answer: "The Claude Partner Network is Anthropic's $100M program to accelerate enterprise Claude deployments through certified implementation partners. Launch partners include Accenture, Deloitte, PwC, McKinsey, and BCG. Certification is a floor, not a ceiling — for production agentic systems, the partners who win are the ones who can point to shipped systems.",
      },
      {
        question: 'Why choose a boutique Claude implementation partner over a Big 4 firm?',
        answer: "Enterprise Claude deployments are agentic systems, not ERP migrations, so the hand-off model that works for SAP fails for Claude. Boutique operators offer direct senior access — the principal who scopes also builds — plus builder credibility from running their own production AI infrastructure, speed (a working prototype in the time a large firm staffs a project), and dogfooding: every recommendation tested on themselves first.",
      },
      {
        question: 'Is Enso Labs a Claude implementation partner?',
        answer: "Enso Labs is a principal-led AI transformation studio that is Claude-certified and Anthropic-credentialed, running Claude-powered production systems across financial services, healthcare, and B2B technology since 2025. The only credential that matters is the system you shipped. Get in touch at https://ensolabs.ai/contact.",
      },
    ],
    body: [
      'Anthropic\'s Claude Partner Network — backed by $100 million in funding — is designed to accelerate enterprise Claude deployments through certified implementation partners. The launch partners include the usual suspects: Accenture, Deloitte, PwC, McKinsey, BCG. The pitch is depth of bench and global reach.',
      'The reality is different. Enterprise Claude deployments are not ERP migrations. They are not lift-and-shift projects that benefit from armies of consultants following a playbook. Agentic AI systems require the person who designed the architecture to also debug the eval harness at 2am. They require the advisor to be in the codebase. The hand-off model that works for SAP does not work for Claude.',
      'Boutique firms have structural advantages in this market. **First: direct senior access.** No account managers, no project coordinators, no layers between the client and the person who understands the system. The principal who scopes the engagement is the same person who writes the MCP server and tunes the eval suite. **Second: builder credibility.** The studio runs its own production AI infrastructure — the Enso Trading Terminal, Strategy to Ship, MCP servers in live environments. When we advise on architecture, we are describing systems we operate.',
      '**Third: speed.** A 50-person consultancy needs three weeks to staff a project. A boutique deploys a working prototype in the same three weeks. **Fourth: dogfooding.** We use Claude to build our own products, run our own analytics, and manage our own operations. Every recommendation we make has been tested on ourselves first.',
      'The Claude Partner Network is good for the ecosystem. It validates enterprise demand and creates a certification layer that helps buyers evaluate partners. But certification is a floor, not a ceiling. The partners who will win production deployments are the ones who can point to shipped systems — not the ones with the largest partner tier.',
      'Enso Labs is a principal-led AI transformation studio. We are Claude-certified, Anthropic-credentialed, and running Claude-powered production systems across financial services, healthcare, and B2B technology. If you are evaluating Claude implementation partners, ask one question: **show me the system you shipped.** That is the only credential that matters.',
    ],
  },
];

export const insightsByPillar = (pillar?: Pillar) =>
  pillar ? INSIGHTS.filter((i) => i.pillar === pillar) : INSIGHTS;

export const getInsight = (slug: string) =>
  INSIGHTS.find((i) => i.slug === slug);
